import { normalizeNotebookLesson } from './lessonScript.js';

const QUICK_EXAMPLE_COPY = Object.freeze({
  ko: {
    title: '빠른 시각 예제',
    uniqueLabel: '교점 하나',
    parallelLabel: '평행·해 없음',
    overlapLabel: '겹치는 직선',
    point3dLabel: '3D 교점',
    line3dLabel: '3D 교선',
    matrixTransformLabel: '행렬 변환',
    nullspaceLabel: '널공간',
    projectionLabel: '투영',
    rankDropLabel: '차원 접힘',
    dependentLabel: '종속 벡터',
    uniqueIntro: '두 방정식 {{L1:expr}}, {{L2:expr}}을 직선으로 그려 공통 조건을 찾습니다',
    uniqueCue: '이제 두 직선의 공통해를 계산해 교점을 직접 나타냅니다',
    uniqueResult: '교점 {{sol}}=`(1, 2)` 하나만 두 조건을 모두 만족하므로 해는 **유일합니다**',
    parallelIntro: '{{L1:expr}}과 {{L2:expr}}은 기울기는 같지만 절편이 다른 두 직선입니다',
    parallelCue: '두 조건을 함께 풀어 공통점이 존재하는지 확인합니다',
    parallelResult: '두 직선은 끝까지 만나지 않습니다\n따라서 이 연립방정식은 **해가 없습니다**',
    overlapIntro: '{{L1:expr}}은 {{L2:expr}}의 2배라서 두 식이 같은 직선을 나타냅니다',
    overlapCue: '두 식의 공통해를 계산해 한 점이 아니라 직선 전체를 드러냅니다',
    overlapResult: '{{sol}}은 같은 직선 위의 모든 점입니다\n따라서 해는 **무수히 많습니다**',
    point3dIntro: '세 방정식 {{P1}}, {{P2}}, {{P3}}을 평면으로 그려 공통 조건을 비교합니다',
    point3dCue: '세 평면을 동시에 만족하는 공통해를 계산합니다',
    point3dResult: '세 평면은 {{sol}}=`(1, 1, 1)` 한 점에서 만나므로 해는 **유일합니다**',
    line3dIntro: '두 평면 {{P1}}, {{P2}}가 겹치는 공통 부분을 찾습니다',
    line3dCue: '두 평면의 공통해를 계산해 교선을 직접 나타냅니다',
    line3dResult: '{{line}}은 `y = 1`, `x + z = 2`를 만족하는 직선 전체입니다\n3차원에서는 두 평면의 해가 **교선**이 될 수 있습니다',
    matrixTransformIntro: '기본 기저벡터 `i`, `j`와 정사각 격자에서 시작합니다',
    matrixTransformCue: '{{A}}를 곱하면 기저벡터와 격자 전체가 함께 움직입니다',
    matrixTransformResult: '`i`→1열, `j`→2열: **열 = 기저의 도착점**',
    nullspaceIntro: '{{n}}과 {{u}}가 만드는 넓이를 먼저 보며 두 입력 방향을 비교합니다',
    nullspaceCue: '이제 {{A}}를 공간 전체에 적용해 두 입력이 어떻게 달라지는지 봅니다',
    nullspaceResult: '{{n}}은 {{zero}}로 사라지고 {{u}}만 남습니다\n0이 되는 입력 방향이 {{A}}의 **널공간**입니다',
    projectionIntro: '단위 정사각형과 {{v}}를 두고 x축 투영 전의 2차원 넓이를 봅니다',
    projectionCue: '이제 {{P}}를 적용해 모든 y성분을 0으로 눌러 버립니다',
    projectionResult: '넓이는 0이 되고 {{v}}는 {{image}} 위로 내려왔습니다\n투영의 출력은 **x축에만** 남습니다',
    rankDropIntro: '세 기저벡터가 만드는 단위 부피를 먼저 확인합니다',
    rankDropCue: '이제 {{A}}를 공간 전체에 적용해 z방향 두께를 0으로 누릅니다',
    rankDropResult: '부피가 0이 되며 3차원 공간이 xy평면으로 접혔습니다\n출력 차원은 **3에서 2로 감소합니다**',
    dependentIntro: '{{p}}와 {{q}}는 같은 직선 위에 있지만, 실제 배수 관계를 확인해 봅니다',
    dependentCue: '{{p}}를 2배해 {{q}}와 같은 위치에 도착하는지 확인합니다',
    dependentResult: '{{scaled}}와 {{q}}가 정확히 겹치고 넓이도 0입니다\n새 방향을 만들지 못하므로 두 벡터는 **선형종속**입니다',
  },
  en: {
    title: 'Quick visual examples',
    uniqueLabel: 'One intersection',
    parallelLabel: 'Parallel · no solution',
    overlapLabel: 'Coincident lines',
    point3dLabel: '3D point',
    line3dLabel: '3D intersection line',
    matrixTransformLabel: 'Matrix transform',
    nullspaceLabel: 'Null space',
    projectionLabel: 'Projection',
    rankDropLabel: 'Rank drop',
    dependentLabel: 'Dependent vectors',
    uniqueIntro: 'Draw {{L1:expr}} and {{L2:expr}} as lines to find their shared condition',
    uniqueCue: 'Now solve both conditions and reveal their intersection explicitly',
    uniqueResult: 'Only {{sol}}=`(1, 2)` satisfies both lines, so the solution is **unique**',
    parallelIntro: '{{L1:expr}} and {{L2:expr}} have the same slope but different intercepts',
    parallelCue: 'Solve the two conditions together to test whether a common point exists',
    parallelResult: 'The lines never meet\nThis system therefore has **no solution**',
    overlapIntro: '{{L1:expr}} is twice {{L2:expr}}, so both equations describe the same line',
    overlapCue: 'Solve the common condition to reveal a full line instead of one point',
    overlapResult: '{{sol}} is every point on the shared line\nThe system has **infinitely many solutions**',
    point3dIntro: 'Draw {{P1}}, {{P2}}, and {{P3}} as planes and compare their shared condition',
    point3dCue: 'Now solve all three planes together',
    point3dResult: 'The planes meet only at {{sol}}=`(1, 1, 1)`, so the solution is **unique**',
    line3dIntro: 'Find the common part shared by planes {{P1}} and {{P2}}',
    line3dCue: 'Solve the two planes and reveal their intersection line',
    line3dResult: '{{line}} is the full line satisfying `y = 1` and `x + z = 2`\nTwo planes in 3D can meet in an **intersection line**',
    matrixTransformIntro: 'Start with the standard basis vectors `i`, `j` and a square grid',
    matrixTransformCue: 'Multiply by {{A}} so the basis vectors and the entire grid move together',
    matrixTransformResult: '`i`→column 1, `j`→column 2: **columns = basis destinations**',
    nullspaceIntro: 'First compare the two input directions using the area made by {{n}} and {{u}}',
    nullspaceCue: 'Now apply {{A}} to the whole space and compare the two inputs',
    nullspaceResult: '{{n}} disappears into {{zero}} while {{u}} survives\nInputs sent to zero form the **null space** of {{A}}',
    projectionIntro: 'Start with the unit square and {{v}} before projecting the 2D area',
    projectionCue: 'Now apply {{P}} and press every y-component down to zero',
    projectionResult: 'The area becomes zero and {{v}} lands on {{image}}\nThe projection output remains **only on the x-axis**',
    rankDropIntro: 'First inspect the unit volume formed by the three basis vectors',
    rankDropCue: 'Now apply {{A}} to the whole space and press the z-thickness to zero',
    rankDropResult: 'The volume vanishes as 3D space folds onto the xy-plane\nThe output dimension **drops from 3 to 2**',
    dependentIntro: '{{p}} and {{q}} lie on the same line; now verify their exact scale relation',
    dependentCue: 'Double {{p}} and check whether it reaches the same endpoint as {{q}}',
    dependentResult: '{{scaled}} and {{q}} coincide exactly, and their area is zero\nThey add no new direction, so they are **linearly dependent**',
  },
  ja: {
    title: 'クイック可視化例',
    uniqueLabel: '1つの交点',
    parallelLabel: '平行・解なし',
    overlapLabel: '重なる直線',
    point3dLabel: '3Dの交点',
    line3dLabel: '3Dの交線',
    matrixTransformLabel: '行列変換',
    nullspaceLabel: '零空間',
    projectionLabel: '射影',
    rankDropLabel: '次元低下',
    dependentLabel: '従属ベクトル',
    uniqueIntro: '{{L1:expr}}と{{L2:expr}}を直線として描き、共通条件を探します',
    uniqueCue: '二つの条件を同時に解き、交点を直接表示します',
    uniqueResult: '{{sol}}=`(1, 2)`だけが両方を満たすため、解は**一意**です',
    parallelIntro: '{{L1:expr}}と{{L2:expr}}は傾きが同じで切片だけが異なります',
    parallelCue: '二つの条件を同時に解き、共通点があるか確認します',
    parallelResult: '二直線は交わりません\nしたがってこの連立方程式は**解なし**です',
    overlapIntro: '{{L1:expr}}は{{L2:expr}}の2倍で、同じ直線を表します',
    overlapCue: '共通解を計算し、一点ではなく直線全体を表示します',
    overlapResult: '{{sol}}は共通直線上のすべての点です\n解は**無数にあります**',
    point3dIntro: '{{P1}}、{{P2}}、{{P3}}を平面として描き、共通条件を比べます',
    point3dCue: '三平面を同時に満たす解を計算します',
    point3dResult: '三平面は{{sol}}=`(1, 1, 1)`だけで交わるため、解は**一意**です',
    line3dIntro: '平面{{P1}}と{{P2}}が共有する部分を探します',
    line3dCue: '二平面の共通解を計算し、交線を表示します',
    line3dResult: '{{line}}は`y = 1`、`x + z = 2`を満たす直線全体です\n3Dでは二平面の解が**交線**になります',
    matrixTransformIntro: '標準基底ベクトル `i`, `j` と正方格子から始めます',
    matrixTransformCue: '{{A}}を掛けると、基底ベクトルと格子全体が一緒に動きます',
    matrixTransformResult: '`i`→第1列, `j`→第2列: **列 = 基底の行き先**',
    nullspaceIntro: '{{n}}と{{u}}が作る面積で二つの入力方向を比べます',
    nullspaceCue: '{{A}}を空間全体に適用して二つの入力の違いを見ます',
    nullspaceResult: '{{n}}は{{zero}}へ消え、{{u}}だけが残ります\n0になる入力方向が{{A}}の**零空間**です',
    projectionIntro: '単位正方形と{{v}}を置き、射影前の2次元面積を見ます',
    projectionCue: '{{P}}を適用してすべてのy成分を0へ押し下げます',
    projectionResult: '面積は0になり、{{v}}は{{image}}上へ移ります\n出力は**x軸上だけ**に残ります',
    rankDropIntro: '三つの基底ベクトルが作る単位体積を先に確認します',
    rankDropCue: '{{A}}を空間全体に適用してz方向の厚みを0にします',
    rankDropResult: '体積が0になり、3D空間がxy平面へ折りたたまれます\n出力次元は**3から2へ低下します**',
    dependentIntro: '{{p}}と{{q}}は同一直線上にあります。倍率関係を確かめます',
    dependentCue: '{{p}}を2倍して{{q}}と同じ終点へ届くか確認します',
    dependentResult: '{{scaled}}と{{q}}が完全に重なり、面積も0です\n新しい方向を作れないため**線形従属**です',
  },
  zh: {
    title: '快速可视化示例',
    uniqueLabel: '唯一交点',
    parallelLabel: '平行·无解',
    overlapLabel: '重合直线',
    point3dLabel: '3D交点',
    line3dLabel: '3D交线',
    matrixTransformLabel: '矩阵变换',
    nullspaceLabel: '零空间',
    projectionLabel: '投影',
    rankDropLabel: '降维',
    dependentLabel: '相关向量',
    uniqueIntro: '把{{L1:expr}}和{{L2:expr}}画成直线，寻找共同条件',
    uniqueCue: '现在同时求解两个条件并直接显示交点',
    uniqueResult: '只有{{sol}}=`(1, 2)`同时满足两条直线，因此解**唯一**',
    parallelIntro: '{{L1:expr}}和{{L2:expr}}斜率相同但截距不同',
    parallelCue: '同时求解两个条件，检查是否存在公共点',
    parallelResult: '两条直线始终不相交\n因此这个方程组**无解**',
    overlapIntro: '{{L1:expr}}是{{L2:expr}}的2倍，两式表示同一条直线',
    overlapCue: '计算共同解，显示整条直线而不是一个点',
    overlapResult: '{{sol}}是公共直线上的所有点\n因此有**无穷多个解**',
    point3dIntro: '把{{P1}}、{{P2}}、{{P3}}画成平面并比较共同条件',
    point3dCue: '现在同时求解三个平面',
    point3dResult: '三个平面只在{{sol}}=`(1, 1, 1)`相交，因此解**唯一**',
    line3dIntro: '寻找平面{{P1}}与{{P2}}共享的部分',
    line3dCue: '求解两个平面并直接显示交线',
    line3dResult: '{{line}}是满足`y = 1`和`x + z = 2`的整条直线\n3D中两个平面的解可以是一条**交线**',
    matrixTransformIntro: '从标准基向量 `i`、`j` 和方格开始',
    matrixTransformCue: '乘以{{A}}，基向量和整个网格会一起移动',
    matrixTransformResult: '`i`→第1列, `j`→第2列：**列 = 基向量的终点**',
    nullspaceIntro: '先用{{n}}和{{u}}形成的面积比较两个输入方向',
    nullspaceCue: '现在把{{A}}作用于整个空间，比较两个输入',
    nullspaceResult: '{{n}}消失到{{zero}}，而{{u}}保留下来\n变成0的输入方向构成{{A}}的**零空间**',
    projectionIntro: '先放置单位正方形和{{v}}，观察投影前的二维面积',
    projectionCue: '现在应用{{P}}，把所有y分量压到0',
    projectionResult: '面积变为0，{{v}}落到{{image}}上\n投影输出**只留在x轴上**',
    rankDropIntro: '先观察三个基向量形成的单位体积',
    rankDropCue: '现在把{{A}}作用于整个空间，将z方向厚度压到0',
    rankDropResult: '体积变为0，3D空间折叠到xy平面\n输出维数**从3降到2**',
    dependentIntro: '{{p}}和{{q}}在同一直线上，现在验证它们的倍数关系',
    dependentCue: '把{{p}}放大2倍，检查是否到达{{q}}的同一终点',
    dependentResult: '{{scaled}}与{{q}}完全重合，面积也为0\n它们不能产生新方向，因此**线性相关**',
  },
});

export const QUICK_EXAMPLE_CONTRACTS = Object.freeze({
  unique: Object.freeze({
    claim: 'Two independent line conditions have one common solution.',
    evidence: 'The authored solver point is visible at the line intersection.',
    representation: '2D graph field.',
    operation: 'Solve the two revealed equations with solution(L1,L2).',
    finalState: 'Both lines, the solution point, and the uniqueness caption remain visible.',
  }),
  parallel: Object.freeze({
    claim: 'Parallel distinct lines produce an inconsistent system.',
    evidence: 'The two visible lines never meet and the authored solve reports no shared point.',
    representation: '2D graph field.',
    operation: 'Solve the two revealed parallel equations.',
    finalState: 'Both parallel lines and the no-solution conclusion remain visible.',
  }),
  overlap: Object.freeze({
    claim: 'Proportional equations have infinitely many common solutions.',
    evidence: 'The authored solver-owned solution is the entire coincident line.',
    representation: '2D graph field.',
    operation: 'Solve the two proportional equations.',
    finalState: 'The coincident equations and highlighted solution line remain visible.',
  }),
  point3d: Object.freeze({
    claim: 'Three independent planes can determine one point.',
    evidence: 'The solver-owned point is visible where all three planes meet.',
    representation: '3D graph field with a deliberate orbit.',
    operation: 'Solve the three revealed planes.',
    finalState: 'All planes and the highlighted point (1,1,1) remain visible.',
  }),
  line3d: Object.freeze({
    claim: 'Two nonparallel planes intersect in a line.',
    evidence: 'The solver-owned intersection line remains visible for free inspection.',
    representation: '3D graph field with an inspect stop.',
    operation: 'Solve the two revealed planes.',
    finalState: 'Both planes and their highlighted intersection line remain visible.',
  }),
  matrixTransform: Object.freeze({
    claim: 'A matrix sends the standard basis to its columns and deforms the whole grid by the same map.',
    evidence: 'The visible basis arrows and square relative grid shear together into the matrix-column directions.',
    representation: '2D transformed graph field.',
    operation: 'Apply A=[[1,1],[0,1]] to the basis vectors and relative grid.',
    finalState: 'The sheared grid, i=(1,0), j=(1,1), matrix card, and conclusion remain visible.',
  }),
  nullspace: Object.freeze({
    claim: 'A rank-one matrix removes its null direction but preserves another input direction.',
    evidence: 'A nonzero vector collapses to the origin while the comparison vector survives.',
    representation: '2D transformed graph field.',
    operation: 'Apply A to the vectors, area, and relative grid.',
    finalState: 'The collapsed grid, surviving vector, and highlighted origin remain visible.',
  }),
  projection: Object.freeze({
    claim: 'Projection onto the x-axis removes all y-direction extent.',
    evidence: 'Unit area collapses to zero and the vector lands on y=0.',
    representation: '2D transformed graph field.',
    operation: 'Apply P to the vector, basis area, and relative grid.',
    finalState: 'The collapsed grid, projected vector, and x-axis image remain visible.',
  }),
  rankDrop3d: Object.freeze({
    claim: 'Removing the z direction drops output dimension from three to two.',
    evidence: 'A live unit volume collapses into the xy-plane.',
    representation: '3D graph field synchronized to a 2D camera view.',
    operation: 'Apply A with view 2d to the basis, volume, and relative grid.',
    finalState: 'The flattened output plane and zero-volume evidence remain visible.',
  }),
  dependent: Object.freeze({
    claim: 'Scalar-multiple vectors are linearly dependent.',
    evidence: 'A named 2p result coincides with q and their determinant is zero.',
    representation: '2D graph field.',
    operation: 'Create scaled = 2 * p, then measure det(p,q).',
    finalState: 'p, q, scaled, and the zero-area result remain visible.',
  }),
});

function localizedCopy(locale) {
  return {
    ...QUICK_EXAMPLE_COPY.en,
    ...(QUICK_EXAMPLE_COPY[locale] ?? {}),
  };
}

export function buildNotebookExamplePresets(locale = 'ko') {
  const copy = localizedCopy(locale);
  const lessons = [
    {
      id: 'unique',
      label: copy.uniqueLabel,
      script: [
        '2d',
        '',
        `// ${copy.uniqueIntro}`,
        'x + y = 3  #L1',
        '2x - y = 0  #L2',
        'checkpoint',
        '',
        `// ${copy.uniqueCue}`,
        'solution(L1, L2)  #sol@',
        `// ${copy.uniqueResult}`,
        'focus hard sol',
      ],
    },
    {
      id: 'parallel',
      label: copy.parallelLabel,
      script: [
        '2d',
        '',
        `// ${copy.parallelIntro}`,
        'x + y = 1  #L1',
        'x + y = 3  #L2',
        'checkpoint',
        '',
        `// ${copy.parallelCue}`,
        'solution(L1, L2)  #none@',
        `// ${copy.parallelResult}`,
        'focus hard L1 L2',
      ],
    },
    {
      id: 'overlap',
      label: copy.overlapLabel,
      script: [
        '2d',
        '',
        `// ${copy.overlapIntro}`,
        '2x + 2y = 4  #L1',
        'x + y = 2  #L2',
        'checkpoint',
        '',
        `// ${copy.overlapCue}`,
        'solution(L1, L2)  #sol@',
        `// ${copy.overlapResult}`,
        'focus hard sol',
      ],
    },
    {
      id: 'point3d',
      label: copy.point3dLabel,
      script: [
        'zoom 4/5',
        '',
        `// ${copy.point3dIntro}`,
        'x + y + z = 3  #P1',
        '2x - y + z = 2  #P2',
        'x + 2y - z = 2  #P3',
        'orbit 6s',
        'checkpoint',
        '',
        `// ${copy.point3dCue}`,
        'solution(P1, P2, P3)  #sol@',
        `// ${copy.point3dResult}`,
        'focus hard sol',
      ],
    },
    {
      id: 'line3d',
      label: copy.line3dLabel,
      script: [
        'zoom 4/5',
        '',
        `// ${copy.line3dIntro}`,
        'x + y + z = 3  #P1',
        'x - y + z = 1  #P2',
        'checkpoint',
        '',
        `// ${copy.line3dCue}`,
        'solution(P1, P2)  #line@',
        `// ${copy.line3dResult}`,
        'focus hard line',
        'inspect',
      ],
    },
    {
      id: 'matrixTransform',
      label: copy.matrixTransformLabel,
      script: [
        '2d',
        'zoom 1',
        'grid off',
        'relative-grid on',
        'basis on',
        'coordinates on',
        '',
        '1 1  #A',
        '0 1',
        '',
        `// ${copy.matrixTransformIntro}`,
        'checkpoint',
        '',
        `// ${copy.matrixTransformCue}`,
        'A',
        `// ${copy.matrixTransformResult}`,
      ],
    },
    {
      id: 'nullspace',
      label: copy.nullspaceLabel,
      script: [
        '2d',
        'grid off',
        'relative-grid on',
        '',
        '1 1  #A',
        '1 1',
        '',
        '1, -1  #n@',
        '1, 1  #u@',
        `// ${copy.nullspaceIntro}`,
        'det(n, u)  #area@',
        'checkpoint',
        '',
        `// ${copy.nullspaceCue}`,
        'A',
        'point(0, 0)  #zero@',
        `// ${copy.nullspaceResult}`,
        'focus hard zero',
      ],
    },
    {
      id: 'projection',
      label: copy.projectionLabel,
      script: [
        '2d',
        'grid off',
        'relative-grid on',
        'basis on',
        '',
        '1 0  #P',
        '0 0',
        '',
        '3, 2  #v@',
        `// ${copy.projectionIntro}`,
        'det(i, j)  #area@',
        'checkpoint',
        '',
        `// ${copy.projectionCue}`,
        'P',
        'y = 0  #image',
        `// ${copy.projectionResult}`,
        'focus hard v image',
      ],
    },
    {
      id: 'rankDrop3d',
      label: copy.rankDropLabel,
      script: [
        'zoom 4/5',
        'grid off',
        'relative-grid on',
        'basis on',
        'coordinates off',
        '',
        '1 0 0  #A',
        '0 1 0',
        '0 0 0',
        '',
        `// ${copy.rankDropIntro}`,
        'det(i, j, k)  #volume@',
        'checkpoint',
        '',
        `// ${copy.rankDropCue}`,
        'A with view 2d',
        `// ${copy.rankDropResult}`,
      ],
    },
    {
      id: 'dependent',
      label: copy.dependentLabel,
      script: [
        '2d',
        '',
        '1, 2  #p@',
        '2, 4  #q@',
        `// ${copy.dependentIntro}`,
        'checkpoint',
        '',
        `// ${copy.dependentCue}`,
        '2 * p  #scaled@',
        'det(p, q)  #area@',
        `// ${copy.dependentResult}`,
        'focus hard scaled q',
      ],
    },
  ].map((lesson) => normalizeNotebookLesson({
    ...lesson,
    contract: QUICK_EXAMPLE_CONTRACTS[lesson.id],
  }));

  return {
    title: copy.title,
    lessons,
    byId: Object.fromEntries(lessons.map((lesson) => [lesson.id, lesson])),
  };
}
