import { normalizeNotebookLesson } from './lessonScript.js';

const BASIC_LESSON_COPY = Object.freeze({
  ko: {
    title: '선형대수 기초 강의',
    hint: '벡터 → 기저 → 행렬 → 부분공간',
    chapterNumberTemplate: '{n}강',
    chapterVectorTitle: '벡터를 계산하는 법',
    chapterBasisTitle: '방향과 좌표를 만드는 법',
    chapterMatrixTitle: '행렬이 공간을 움직이는 법',
    chapterSystemTitle: '방정식을 행렬로 푸는 법',
    chapterSpaceTitle: '부분공간과 특별한 방향',
    vectorLabel: '벡터와 스칼라',
    vectorIntro: '**벡터**는 크기와 방향을 함께 가진 화살표입니다',
    vectorDoubleCue: '이제 {{v}}에 2를 곱해 길이를 두 배로 늘립니다',
    vectorDoubleResult: '방향은 그대로이고 **길이만 두 배**가 되었습니다',
    vectorFlipCue: '이번에는 현재 {{v}}에 `-1/2`을 곱합니다',
    vectorFlipResult: '음수를 곱하면 크기뿐 아니라 **방향도 반대**가 됩니다',
    additionLabel: '벡터 덧셈',
    additionIntro: '{{u}}와 {{v}}를 같은 원점에서 비교합니다',
    additionCue: '두 벡터를 더하면 성분끼리 더한 새로운 벡터가 만들어집니다',
    additionResult: '{{s}}는 `{{u}} + {{v}} = (3, 3)`인 **합벡터**입니다',
    combinationLabel: '선형결합',
    combinationIntro: '**선형결합**은 각 벡터에 계수를 곱한 뒤 더하는 방법입니다',
    combinationUnitCue: '먼저 {{u}}와 {{v}}를 한 개씩 더합니다',
    combinationScaleCue: '이제 {{u}}의 계수만 2로 바꿉니다',
    combinationResult: '합 {{out}}도 함께 이동합니다\n이처럼 계수를 바꾸어 만드는 합이 **선형결합**입니다',
    matrixColumnsLabel: '행렬의 열',
    matrixColumnsIntro: '{{A}}의 열 {{c1}}, {{c2}}는 기저벡터 `i`, `j`가 도착할 곳입니다',
    matrixColumnsCue: '열벡터를 숨기고 {{A}}를 적용해 기저와 격자를 같은 목적지로 보냅니다',
    matrixColumnsResult: '`i`는 첫째 열로, `j`는 둘째 열로 이동했습니다\n행렬은 **기저의 새 목적지를 나란히 적은 것**입니다',
    transformLabel: '확대와 회전',
    transformIntro: '대각행렬 {{S}}는 축 방향을 유지한 채 x방향 길이를 2배로 늘립니다',
    transformCue: '{{S}}를 적용해 기저와 격자의 x방향 간격을 늘립니다',
    transformResult: 'x축 방향만 늘어나 공간이 가로로 확대되었습니다',
    transformRotateCue: '이번에는 회전행렬 {{R}}로 기저와 격자를 90도 돌립니다',
    transformRotateResult: '두 축과 격자가 함께 회전했습니다\n행렬곱은 **좌표 격자 전체의 변환**입니다',
    determinantLabel: '행렬식',
    determinantIntro: '**행렬식**은 두 벡터가 만드는 부호 있는 넓이입니다',
    determinantResult: '`det({{a}}, {{b}}) = 3`이므로 평행사변형의 넓이는 **3**입니다',
    determinantZeroCue: '이번에는 같은 방향의 두 벡터를 비교합니다',
    determinantZeroResult: '`det({{p}}, {{q}}) = 0`이면 넓이가 사라집니다\n두 벡터는 **선형종속**입니다',
    dotLabel: '내적과 직교',
    dotIntro: '**내적**은 두 벡터가 같은 방향을 얼마나 바라보는지 재는 수입니다',
    dotResult: '`dot({{u}}, {{v}}) = 0`입니다\n두 벡터는 서로 **직교**합니다',
    independenceLabel: '선형독립과 종속',
    independenceIntro: '{{a}}와 {{b}}는 어느 하나도 다른 벡터의 배수가 아닌 두 방향입니다',
    independenceResult: '`α{{a}} + β{{b}} = 0`은 `α=β=0`일 때만 가능합니다\n그래서 두 벡터는 **선형독립**입니다',
    dependenceCue: '이번에는 한 벡터가 다른 벡터의 배수인 경우를 봅니다',
    dependenceResult: '{{q}}는 `2{{p}}`라서 같은 방향을 반복합니다\n새 방향을 만들지 못하므로 두 벡터는 **선형종속**입니다',
    basisLabel: '기저와 좌표',
    basisIntro: '{{b1}}, {{b2}}처럼 공간의 모든 방향을 만들 수 있는 독립 벡터가 **기저**입니다',
    basisCoordinateCue: '이 기저에서 좌표 `(2, 1)`은 {{b1}}을 2개, {{b2}}를 1개 사용한다는 뜻입니다',
    basisResult: '기저좌표 `(2, 1)`의 실제 위치는 `(1, 3)`입니다\n좌표는 **기저를 섞는 계수**입니다',
    systemLabel: '연립방정식 두 관점',
    systemColumnIntro: '열 관점에서는 {{A}}의 열벡터 {{c1}}, {{c2}}를 섞어 목표 {{b}}를 만듭니다',
    systemScaleCue: '해 `(2, 1)`에 맞춰 {{c1}}의 계수를 2로 바꿉니다',
    systemColumnResult: '합 {{out}}이 목표 {{b}}에 도착했습니다\n열 관점의 해는 **각 열의 사용 개수**입니다',
    systemRowIntro: '행 관점에서는 같은 문제를 두 직선 {{R1}}, {{R2}}의 공통 조건으로 봅니다',
    systemResult: '두 직선의 교점 {{sol}}도 `(2, 1)`입니다\n두 관점은 **같은 해**를 설명합니다',
    inverseLabel: '역행렬',
    inverseIntro: '{{A}}가 공간을 움직이면 {{x}}도 `(1, 1)`에서 `(3, 2)`로 이동합니다',
    inverseForward: '먼저 {{A}}를 적용해 정방향 변환을 확인합니다',
    inverseCue: '이제 {{A}}의 역행렬 {{B}}를 적용해 변환을 되돌립니다',
    inverseResult: '{{x}}가 다시 `(1, 1)`로 돌아왔습니다\n역행렬은 원래 변환을 **취소하는 변환**입니다',
    projectionLabel: '투영',
    projectionIntro: '**투영**은 벡터를 한 축이나 부분공간 위로 비추는 그림자입니다',
    projectionResult: '{{P}}가 y성분을 없애 {{v}}를 `(3, 0)`으로 내렸습니다',
    projectionAgainCue: '이미 x축 위에 있는 결과에 {{P}}를 한 번 더 적용합니다',
    projectionAgainResult: '두 번째에는 아무것도 변하지 않습니다\n그래서 투영행렬은 `P² = P`를 만족합니다',
    subspaceLabel: '열공간과 널공간',
    subspaceIntro: '{{A}}는 3차원 공간의 z방향을 없애는 행렬입니다',
    subspaceCollapseCue: '부피와 상대격자를 함께 눌러 출력이 도달하는 공간을 확인합니다',
    subspaceColumnResult: '부피가 0이 되고 모든 출력이 xy평면에 모였습니다\n이 평면이 {{A}}의 **열공간**입니다',
    subspaceNullCue: '이번에는 z축 위의 벡터 {{n}}을 같은 {{A}}에 넣습니다',
    subspaceNullResult: '{{n}}이 원점으로 완전히 사라졌습니다\n이렇게 0이 되는 입력 방향이 **널공간**입니다',
    eigenLabel: '고유벡터',
    eigenIntro: '{{e}}는 {{D}}를 통과해도 방향이 유지되고, {{q}}는 방향이 바뀝니다',
    eigenCue: '{{D}}를 적용해 두 벡터의 방향 변화를 비교합니다',
    eigenResult: '{{e}}는 같은 직선 위에서 길이만 2배가 되었습니다\n이처럼 방향이 보존되는 벡터가 **고유벡터**입니다',
  },
  en: {
    title: 'Linear Algebra Basics',
    hint: 'Vectors → bases → matrices → subspaces',
    chapterNumberTemplate: 'Unit {n}',
    chapterVectorTitle: 'Computing with vectors',
    chapterBasisTitle: 'Directions and coordinates',
    chapterMatrixTitle: 'How matrices move space',
    chapterSystemTitle: 'Solving equations with matrices',
    chapterSpaceTitle: 'Subspaces and special directions',
    vectorLabel: 'Vectors & scalars',
    vectorIntro: 'A **vector** is an arrow with both magnitude and direction',
    vectorDoubleCue: 'Now multiply {{v}} by 2 to double its length',
    vectorDoubleResult: 'The direction stays fixed while **only the length doubles**',
    vectorFlipCue: 'Now multiply the current {{v}} by `-1/2`',
    vectorFlipResult: 'A negative scalar changes the size and **reverses the direction**',
    additionLabel: 'Vector addition',
    additionIntro: 'Compare {{u}} and {{v}} from the same origin',
    additionCue: 'Adding vectors adds their components to create a new vector',
    additionResult: '{{s}} is the **sum vector** `{{u}} + {{v}} = (3, 3)`',
    combinationLabel: 'Linear combinations',
    combinationIntro: 'A **linear combination** multiplies each vector by a coefficient and then adds them',
    combinationUnitCue: 'First add one copy each of {{u}} and {{v}}',
    combinationScaleCue: 'Now change only the coefficient of {{u}} to 2',
    combinationResult: 'The sum {{out}} moves with it\nChanging coefficients this way creates a **linear combination**',
    matrixColumnsLabel: 'Matrix columns',
    matrixColumnsIntro: 'Columns {{c1}} and {{c2}} of {{A}} are the destinations of basis vectors `i` and `j`',
    matrixColumnsCue: 'Hide the column arrows, then apply {{A}} to send the basis and grid to those destinations',
    matrixColumnsResult: '`i` reached the first column and `j` reached the second\nA matrix **lists the new destinations of the basis**',
    transformLabel: 'Scaling & rotation',
    transformIntro: 'Diagonal matrix {{S}} keeps the axis directions but doubles horizontal length',
    transformCue: 'Apply {{S}} to widen the x-spacing of the basis and grid',
    transformResult: 'Only the x direction stretched, so the space became wider',
    transformRotateCue: 'Now use rotation matrix {{R}} to turn the basis and grid by 90 degrees',
    transformRotateResult: 'Both axes and the grid rotated together\nMatrix multiplication transforms the **entire coordinate grid**',
    determinantLabel: 'Determinants',
    determinantIntro: 'The **determinant** is the signed area made by two vectors',
    determinantResult: '`det({{a}}, {{b}}) = 3`, so the parallelogram has area **3**',
    determinantZeroCue: 'Now compare two vectors pointing in the same direction',
    determinantZeroResult: 'When `det({{p}}, {{q}}) = 0`, the area disappears\nThe vectors are **linearly dependent**',
    dotLabel: 'Dot products & orthogonality',
    dotIntro: 'The **dot product** measures how much two vectors face the same direction',
    dotResult: '`dot({{u}}, {{v}}) = 0`\nThe two vectors are **orthogonal**',
    independenceLabel: 'Independence & dependence',
    independenceIntro: 'Neither {{a}} nor {{b}} is a scalar multiple of the other, so they provide two directions',
    independenceResult: '`α{{a}} + β{{b}} = 0` only when `α=β=0`\nThe two vectors are **linearly independent**',
    dependenceCue: 'Now consider a vector that is a multiple of the other',
    dependenceResult: '{{q}} is `2{{p}}`, so it repeats the same direction\nIt adds no new direction, making the pair **linearly dependent**',
    basisLabel: 'Bases & coordinates',
    basisIntro: 'Independent vectors such as {{b1}} and {{b2}} that generate every direction form a **basis**',
    basisCoordinateCue: 'In this basis, coordinates `(2, 1)` mean two copies of {{b1}} and one of {{b2}}',
    basisResult: 'Basis coordinates `(2, 1)` land at the actual point `(1, 3)`\nCoordinates are **coefficients relative to a basis**',
    systemLabel: 'Two views of a system',
    systemColumnIntro: 'The column view mixes columns {{c1}} and {{c2}} of {{A}} to make target {{b}}',
    systemScaleCue: 'Match the solution `(2, 1)` by changing the coefficient of {{c1}} to 2',
    systemColumnResult: 'The sum {{out}} reached target {{b}}\nThe column-view solution gives **how many of each column** to use',
    systemRowIntro: 'The row view treats the same problem as the shared conditions of lines {{R1}} and {{R2}}',
    systemResult: 'Their intersection {{sol}} is also `(2, 1)`\nBoth views describe the **same solution**',
    inverseLabel: 'Inverse matrices',
    inverseIntro: 'When {{A}} moves space, {{x}} moves from `(1, 1)` to `(3, 2)`',
    inverseForward: 'First apply {{A}} to see the forward transformation',
    inverseCue: 'Now apply inverse matrix {{B}} to undo {{A}}',
    inverseResult: '{{x}} returned to `(1, 1)`\nAn inverse matrix **cancels the original transformation**',
    projectionLabel: 'Projection',
    projectionIntro: 'A **projection** is the shadow of a vector on an axis or subspace',
    projectionResult: '{{P}} removed the y component and lowered {{v}} to `(3, 0)`',
    projectionAgainCue: 'Apply {{P}} again to a result that already lies on the x-axis',
    projectionAgainResult: 'Nothing changes the second time\nThat is why a projection matrix satisfies `P² = P`',
    subspaceLabel: 'Column space & null space',
    subspaceIntro: '{{A}} removes the z direction from three-dimensional space',
    subspaceCollapseCue: 'Collapse the volume and relative grid to see where outputs can reach',
    subspaceColumnResult: 'The volume became zero and every output lies in the xy-plane\nThis plane is the **column space** of {{A}}',
    subspaceNullCue: 'Now feed the z-axis vector {{n}} into the same {{A}}',
    subspaceNullResult: '{{n}} disappeared completely into the origin\nInput directions sent to zero form the **null space**',
    eigenLabel: 'Eigenvectors',
    eigenIntro: '{{e}} keeps its direction through {{D}}, while {{q}} changes direction',
    eigenCue: 'Apply {{D}} and compare the direction of the two vectors',
    eigenResult: '{{e}} stayed on the same line and only doubled in length\nA vector whose direction is preserved is an **eigenvector**',
  },
  ja: {
    title: '線形代数の基礎講義',
    hint: 'ベクトル → 基底 → 行列 → 部分空間',
    chapterNumberTemplate: '第{n}講',
    chapterVectorTitle: 'ベクトルの計算',
    chapterBasisTitle: '方向と座標の作り方',
    chapterMatrixTitle: '行列が空間を動かす仕組み',
    chapterSystemTitle: '行列で方程式を解く',
    chapterSpaceTitle: '部分空間と特別な方向',
    vectorLabel: 'ベクトルとスカラー',
    vectorIntro: '**ベクトル**は大きさと向きを持つ矢印です',
    vectorDoubleCue: '{{v}}に2を掛けて長さを2倍にします',
    vectorDoubleResult: '向きは同じで、**長さだけが2倍**になります',
    vectorFlipCue: '今の{{v}}に`-1/2`を掛けます',
    vectorFlipResult: '負の数を掛けると**向きも反対**になります',
    additionLabel: 'ベクトルの加法',
    additionIntro: '{{u}}と{{v}}を同じ原点から比べます',
    additionCue: '成分ごとに足すと新しいベクトルができます',
    additionResult: '{{s}}は`{{u}} + {{v}} = (3, 3)`という**和ベクトル**です',
    combinationLabel: '線形結合',
    combinationIntro: '**線形結合**は各ベクトルに係数を掛けて足す方法です',
    combinationUnitCue: 'まず{{u}}と{{v}}を一つずつ足します',
    combinationScaleCue: '{{u}}の係数だけを2に変えます',
    combinationResult: '和{{out}}も一緒に動きます\n係数を変えて作る和が**線形結合**です',
    matrixColumnsLabel: '行列の列',
    matrixColumnsIntro: '{{A}}の列{{c1}}, {{c2}}は基底ベクトル`i`, `j`の行き先です',
    matrixColumnsCue: '列の矢印を隠し、{{A}}で基底と格子を同じ行き先へ動かします',
    matrixColumnsResult: '`i`は第一列へ、`j`は第二列へ移動しました\n行列は**基底の新しい行き先を並べたもの**です',
    transformLabel: '拡大と回転',
    transformIntro: '対角行列{{S}}は軸の向きを保ち、x方向の長さを2倍にします',
    transformCue: '{{S}}を適用して基底と格子のx方向の間隔を広げます',
    transformResult: 'x方向だけが伸び、空間が横に拡大しました',
    transformRotateCue: '次は回転行列{{R}}で基底と格子を90度回します',
    transformRotateResult: '二つの軸と格子が一緒に回転しました\n行列積は**座標格子全体の変換**です',
    determinantLabel: '行列式',
    determinantIntro: '**行列式**は二つのベクトルが作る符号付き面積です',
    determinantResult: '`det({{a}}, {{b}}) = 3`なので面積は**3**です',
    determinantZeroCue: '次は同じ方向の二つのベクトルを比べます',
    determinantZeroResult: '`det({{p}}, {{q}}) = 0`なら面積は消えます\n二つのベクトルは**線形従属**です',
    dotLabel: '内積と直交',
    dotIntro: '**内積**は二つのベクトルが同じ方向をどれだけ向くかを測ります',
    dotResult: '`dot({{u}}, {{v}}) = 0`です\n二つのベクトルは**直交**します',
    independenceLabel: '線形独立と従属',
    independenceIntro: '{{a}}と{{b}}は互いに相手のスカラー倍ではない二つの方向です',
    independenceResult: '`α{{a}} + β{{b}} = 0`は`α=β=0`のときだけです\nしたがって二つは**線形独立**です',
    dependenceCue: '次は一方が他方の倍数である場合を見ます',
    dependenceResult: '{{q}}は`2{{p}}`なので同じ方向を繰り返します\n新しい方向を作れず、二つは**線形従属**です',
    basisLabel: '基底と座標',
    basisIntro: '{{b1}}, {{b2}}のように全方向を作れる独立ベクトルが**基底**です',
    basisCoordinateCue: 'この基底で座標`(2, 1)`は{{b1}}を2個、{{b2}}を1個使う意味です',
    basisResult: '基底座標`(2, 1)`の実際の位置は`(1, 3)`です\n座標は**基底を混ぜる係数**です',
    systemLabel: '連立方程式の二つの見方',
    systemColumnIntro: '列の見方では{{A}}の列{{c1}}, {{c2}}を混ぜて目標{{b}}を作ります',
    systemScaleCue: '解`(2, 1)`に合わせて{{c1}}の係数を2に変えます',
    systemColumnResult: '和{{out}}が目標{{b}}に到着しました\n解は**各列を使う個数**です',
    systemRowIntro: '行の見方では同じ問題を直線{{R1}}, {{R2}}の共通条件として見ます',
    systemResult: '交点{{sol}}も`(2, 1)`です\n二つの見方は**同じ解**を説明します',
    inverseLabel: '逆行列',
    inverseIntro: '{{A}}が空間を動かすと{{x}}も`(1, 1)`から`(3, 2)`へ移動します',
    inverseForward: 'まず{{A}}を適用して順方向の変換を確認します',
    inverseCue: '次に{{A}}の逆行列{{B}}で変換を元に戻します',
    inverseResult: '{{x}}が`(1, 1)`に戻りました\n逆行列は元の変換を**打ち消す変換**です',
    projectionLabel: '射影',
    projectionIntro: '**射影**はベクトルを軸や部分空間へ映した影です',
    projectionResult: '{{P}}がy成分を消し、{{v}}を`(3, 0)`へ下ろしました',
    projectionAgainCue: 'すでにx軸上にある結果へ{{P}}をもう一度適用します',
    projectionAgainResult: '二回目は何も変わりません\nしたがって射影行列は`P² = P`を満たします',
    subspaceLabel: '列空間と零空間',
    subspaceIntro: '{{A}}は3次元空間のz方向を消す行列です',
    subspaceCollapseCue: '体積と相対格子を一緒に潰し、出力が届く空間を確認します',
    subspaceColumnResult: '体積が0になり、全出力がxy平面に集まりました\nこの平面が{{A}}の**列空間**です',
    subspaceNullCue: '次はz軸上のベクトル{{n}}を同じ{{A}}へ入れます',
    subspaceNullResult: '{{n}}が原点へ完全に消えました\n0になる入力方向が**零空間**です',
    eigenLabel: '固有ベクトル',
    eigenIntro: '{{e}}は{{D}}を通っても向きを保ち、{{q}}は向きが変わります',
    eigenCue: '{{D}}を適用して二つのベクトルの向きを比べます',
    eigenResult: '{{e}}は同じ直線上で長さだけ2倍になりました\n向きが保たれるベクトルが**固有ベクトル**です',
  },
  zh: {
    title: '线性代数基础课',
    hint: '向量 → 基 → 矩阵 → 子空间',
    chapterNumberTemplate: '第{n}课',
    chapterVectorTitle: '向量的计算方法',
    chapterBasisTitle: '方向与坐标的构成',
    chapterMatrixTitle: '矩阵如何移动空间',
    chapterSystemTitle: '用矩阵求解方程',
    chapterSpaceTitle: '子空间与特殊方向',
    vectorLabel: '向量与标量',
    vectorIntro: '**向量**是同时具有大小和方向的箭头',
    vectorDoubleCue: '现在把{{v}}乘以2，使长度变为两倍',
    vectorDoubleResult: '方向不变，**只有长度变为两倍**',
    vectorFlipCue: '再把当前{{v}}乘以`-1/2`',
    vectorFlipResult: '乘以负数时，**方向也会反转**',
    additionLabel: '向量加法',
    additionIntro: '从同一个原点比较{{u}}与{{v}}',
    additionCue: '向量相加就是把对应分量相加',
    additionResult: '{{s}}是`{{u}} + {{v}} = (3, 3)`的**和向量**',
    combinationLabel: '线性组合',
    combinationIntro: '**线性组合**是给每个向量乘系数后再相加',
    combinationUnitCue: '先把{{u}}与{{v}}各取一个相加',
    combinationScaleCue: '现在只把{{u}}的系数改为2',
    combinationResult: '和{{out}}也会一起移动\n改变系数得到的和就是**线性组合**',
    matrixColumnsLabel: '矩阵的列',
    matrixColumnsIntro: '{{A}}的列{{c1}}, {{c2}}就是基向量`i`, `j`的目的地',
    matrixColumnsCue: '隐藏列向量后应用{{A}}，让基与网格移动到同样的目的地',
    matrixColumnsResult: '`i`到达第一列，`j`到达第二列\n矩阵就是**把基的新目的地并排写出**',
    transformLabel: '缩放与旋转',
    transformIntro: '对角矩阵{{S}}保持轴的方向，同时把x方向长度放大两倍',
    transformCue: '应用{{S}}，拉宽基与网格在x方向的间距',
    transformResult: '只有x方向被拉伸，空间横向放大',
    transformRotateCue: '接着用旋转矩阵{{R}}把基与网格旋转90度',
    transformRotateResult: '两个坐标轴与网格一起旋转\n矩阵乘法变换的是**整个坐标网格**',
    determinantLabel: '行列式',
    determinantIntro: '**行列式**是两个向量形成的带符号面积',
    determinantResult: '`det({{a}}, {{b}}) = 3`，所以平行四边形面积为**3**',
    determinantZeroCue: '接着比较两个同方向向量',
    determinantZeroResult: '当`det({{p}}, {{q}}) = 0`时面积消失\n这两个向量**线性相关**',
    dotLabel: '内积与正交',
    dotIntro: '**内积**衡量两个向量朝向同一方向的程度',
    dotResult: '`dot({{u}}, {{v}}) = 0`\n两个向量彼此**正交**',
    independenceLabel: '线性无关与相关',
    independenceIntro: '{{a}}与{{b}}都不是另一个向量的倍数，因此提供两个方向',
    independenceResult: '`α{{a}} + β{{b}} = 0`只有在`α=β=0`时成立\n所以它们**线性无关**',
    dependenceCue: '再看一个向量是另一个向量倍数的情况',
    dependenceResult: '{{q}}是`2{{p}}`，重复了同一方向\n它没有增加新方向，所以二者**线性相关**',
    basisLabel: '基与坐标',
    basisIntro: '像{{b1}}, {{b2}}这样能生成所有方向的无关向量构成一组**基**',
    basisCoordinateCue: '在这组基中，坐标`(2, 1)`表示使用2个{{b1}}和1个{{b2}}',
    basisResult: '基坐标`(2, 1)`对应的实际位置是`(1, 3)`\n坐标就是**相对于基的系数**',
    systemLabel: '方程组的两种视角',
    systemColumnIntro: '列视角混合{{A}}的列{{c1}}, {{c2}}来得到目标{{b}}',
    systemScaleCue: '按照解`(2, 1)`把{{c1}}的系数改为2',
    systemColumnResult: '和{{out}}到达目标{{b}}\n列视角的解表示**每一列使用多少次**',
    systemRowIntro: '行视角把同一问题看成直线{{R1}}, {{R2}}的共同条件',
    systemResult: '交点{{sol}}同样是`(2, 1)`\n两种视角描述**同一个解**',
    inverseLabel: '逆矩阵',
    inverseIntro: '{{A}}移动空间时，{{x}}也从`(1, 1)`移动到`(3, 2)`',
    inverseForward: '先应用{{A}}观察正向变换',
    inverseCue: '再应用{{A}}的逆矩阵{{B}}撤销变换',
    inverseResult: '{{x}}回到`(1, 1)`\n逆矩阵会**抵消原来的变换**',
    projectionLabel: '投影',
    projectionIntro: '**投影**是向量落在某条轴或子空间上的影子',
    projectionResult: '{{P}}消去y分量，把{{v}}降到`(3, 0)`',
    projectionAgainCue: '对已经位于x轴上的结果再次应用{{P}}',
    projectionAgainResult: '第二次什么也不改变\n因此投影矩阵满足`P² = P`',
    subspaceLabel: '列空间与零空间',
    subspaceIntro: '{{A}}会消去三维空间的z方向',
    subspaceCollapseCue: '同时压缩体积和相对网格，观察输出能够到达哪里',
    subspaceColumnResult: '体积变为0，所有输出聚集到xy平面\n该平面就是{{A}}的**列空间**',
    subspaceNullCue: '现在把z轴向量{{n}}送入同一个{{A}}',
    subspaceNullResult: '{{n}}完全消失到原点\n被映射为0的输入方向构成**零空间**',
    eigenLabel: '特征向量',
    eigenIntro: '{{e}}经过{{D}}后方向保持不变，而{{q}}的方向会改变',
    eigenCue: '应用{{D}}并比较两个向量的方向变化',
    eigenResult: '{{e}}仍在同一直线上，只是长度变为两倍\n方向保持不变的向量就是**特征向量**',
  },
});

export function buildNotebookBasicLessons(locale = 'ko') {
  const copy = BASIC_LESSON_COPY[locale] ?? BASIC_LESSON_COPY.en;
  const lessons = [
      {
        id: 'vector-scalar',
        label: copy.vectorLabel,
        script: [
          '2d',
          'zoom 1',
          'coordinates on',
          '',
          `// ${copy.vectorIntro}`,
          '2, 1  #v@',
          'focus v',
          'checkpoint',
          '',
          'focus -',
          `// ${copy.vectorDoubleCue}`,
          'v * 2',
          `// ${copy.vectorDoubleResult}`,
          'checkpoint',
          '',
          `// ${copy.vectorFlipCue}`,
          'v * -1/2',
          `// ${copy.vectorFlipResult}`,
          'focus v',
        ],
      },
      {
        id: 'vector-addition',
        label: copy.additionLabel,
        script: [
          '2d',
          'zoom 9/10',
          'coordinates on',
          '',
          '1, 2  #u@',
          '2, 1  #v@',
          `// ${copy.additionIntro}`,
          'focus u v',
          'checkpoint',
          '',
          'focus -',
          `// ${copy.additionCue}`,
          'sum(u, v)  #s@',
          `// ${copy.additionResult}`,
        ],
      },
      {
        id: 'linear-combination',
        label: copy.combinationLabel,
        script: [
          '2d',
          'zoom 4/5',
          'coordinates on',
          '',
          '1, 2  #u@',
          '2, -1  #v@',
          `// ${copy.combinationIntro}`,
          'focus u v',
          'checkpoint',
          '',
          'focus -',
          `// ${copy.combinationUnitCue}`,
          'sum(u, v)  #out@',
          'checkpoint',
          '',
          `// ${copy.combinationScaleCue}`,
          'u * 2',
          `// ${copy.combinationResult}`,
        ],
      },
      {
        id: 'linear-independence',
        label: copy.independenceLabel,
        script: [
          '2d',
          'zoom 1',
          'coordinates on',
          '',
          '2, 1  #a@',
          '-1, 2  #b@',
          `// ${copy.independenceIntro}`,
          'focus a b',
          'checkpoint',
          '',
          `// ${copy.independenceResult}`,
          'checkpoint',
          '',
          'focus -',
          'clear',
          '1, 1  #p@',
          `// ${copy.dependenceCue}`,
          '2, 2  #q@',
          `// ${copy.dependenceResult}`,
          'focus p q',
        ],
      },
      {
        id: 'basis-coordinates',
        label: copy.basisLabel,
        script: [
          '2d',
          'zoom 9/10',
          'coordinates on',
          '',
          '1, 1  #b1@',
          '-1, 1  #b2@',
          `// ${copy.basisIntro}`,
          'focus b1 b2',
          'checkpoint',
          '',
          'focus -',
          'sum(b1, b2)  #x@',
          `// ${copy.basisCoordinateCue}`,
          'checkpoint',
          '',
          'b1 * 2',
          `// ${copy.basisResult}`,
          'focus x',
        ],
      },
      {
        id: 'matrix-columns',
        label: copy.matrixColumnsLabel,
        script: [
          '2d',
          'zoom 9/10',
          'grid on',
          'relative-grid off',
          'basis off',
          'coordinates on',
          '',
          '1 1  #A',
          '0 1',
          '',
          'col(A, 1)  #c1@',
          'col(A, 2)  #c2@',
          `// ${copy.matrixColumnsIntro}`,
          'focus c1 c2',
          'checkpoint',
          '',
          'focus -',
          'c1 -',
          'c2 -',
          'basis on',
          'relative-grid on',
          `// ${copy.matrixColumnsCue}`,
          'A',
          `// ${copy.matrixColumnsResult}`,
        ],
      },
      {
        id: 'matrix-transform',
        label: copy.transformLabel,
        script: [
          '2d',
          'zoom 4/5',
          'grid on',
          'relative-grid on',
          'basis on',
          'coordinates off',
          '',
          '2 0  #S',
          '0 1',
          `// ${copy.transformIntro}`,
          'checkpoint',
          '',
          `// ${copy.transformCue}`,
          'S',
          `// ${copy.transformResult}`,
          'checkpoint',
          '',
          'clear',
          'space reset',
          '0 -1  #R',
          '1 0',
          `// ${copy.transformRotateCue}`,
          'checkpoint',
          '',
          'R',
          `// ${copy.transformRotateResult}`,
        ],
      },
      {
        id: 'determinant',
        label: copy.determinantLabel,
        script: [
          '2d',
          'zoom 1',
          'coordinates on',
          '',
          '2, 1  #a@',
          '1, 2  #b@',
          `// ${copy.determinantIntro}`,
          'det(a, b)  #area@',
          'focus a b',
          'checkpoint',
          '',
          `// ${copy.determinantResult}`,
          'checkpoint',
          '',
          'focus -',
          'clear',
          `// ${copy.determinantZeroCue}`,
          '1, 1  #p@',
          '2, 2  #q@',
          'det(p, q)  #zero@',
          `// ${copy.determinantZeroResult}`,
          'focus p q',
        ],
      },
      {
        id: 'dot-orthogonality',
        label: copy.dotLabel,
        script: [
          '2d',
          'zoom 1',
          'coordinates on',
          '',
          '2, 1  #u@',
          '-1, 2  #v@',
          `// ${copy.dotIntro}`,
          'focus u v',
          'checkpoint',
          '',
          'focus -',
          'dot(u, v)  #d@',
          `// ${copy.dotResult}`,
          'focus u v',
        ],
      },
      {
        id: 'system-two-views',
        label: copy.systemLabel,
        script: [
          '2d',
          'zoom 4/5',
          'coordinates on',
          '',
          '1 1  #A',
          '2 -1',
          '',
          'col(A, 1)  #c1@',
          'col(A, 2)  #c2@',
          'point(3, 3)  #b@',
          `// ${copy.systemColumnIntro}`,
          'focus c1 c2',
          'checkpoint',
          '',
          'focus -',
          'sum(c1, c2)  #out@',
          `// ${copy.systemScaleCue}`,
          'c1 * 2',
          `// ${copy.systemColumnResult}`,
          'focus out b',
          'checkpoint',
          '',
          'focus -',
          'clear',
          'A +',
          'x + y = 3  #R1',
          '2x - y = 3  #R2',
          `// ${copy.systemRowIntro}`,
          'checkpoint',
          '',
          'solution(R1, R2)  #sol@',
          `// ${copy.systemResult}`,
          'focus sol',
        ],
      },
      {
        id: 'inverse-matrix',
        label: copy.inverseLabel,
        script: [
          '2d',
          'zoom 9/10',
          'grid off',
          'relative-grid on',
          'coordinates on',
          '',
          '2 1  #A',
          '1 1',
          '',
          '1 -1  #B',
          '-1 2',
          '',
          '1, 1  #x@',
          `// ${copy.inverseIntro}`,
          'checkpoint',
          '',
          `// ${copy.inverseForward}`,
          'A',
          'checkpoint',
          '',
          `// ${copy.inverseCue}`,
          'B',
          `// ${copy.inverseResult}`,
          'focus x',
        ],
      },
      {
        id: 'projection',
        label: copy.projectionLabel,
        script: [
          '2d',
          'zoom 9/10',
          'grid off',
          'relative-grid on',
          'coordinates on',
          '',
          '1 0  #P',
          '0 0',
          '',
          '3, 2  #v@',
          `// ${copy.projectionIntro}`,
          'checkpoint',
          '',
          'P',
          `// ${copy.projectionResult}`,
          'focus v',
          'checkpoint',
          '',
          'focus -',
          `// ${copy.projectionAgainCue}`,
          'P',
          `// ${copy.projectionAgainResult}`,
          'focus v',
        ],
      },
      {
        id: 'column-null-space',
        label: copy.subspaceLabel,
        script: [
          '3d',
          'zoom 4/5',
          'grid off',
          'relative-grid on',
          'coordinates off',
          'basis on',
          '',
          '1 0 0  #A',
          '0 1 0',
          '0 0 0',
          '',
          'det(i, j, k)  #volume@',
          `// ${copy.subspaceIntro}`,
          'checkpoint',
          '',
          `// ${copy.subspaceCollapseCue}`,
          'A with view 2d',
          `// ${copy.subspaceColumnResult}`,
          'checkpoint',
          '',
          'clear',
          'space reset',
          'view 3d',
          'basis off',
          'coordinates on',
          '0, 0, 2  #n@',
          `// ${copy.subspaceNullCue}`,
          'checkpoint',
          '',
          'A',
          `// ${copy.subspaceNullResult}`,
          'focus n',
        ],
      },
      {
        id: 'eigenvector',
        label: copy.eigenLabel,
        script: [
          '2d',
          'zoom 9/10',
          'grid off',
          'relative-grid on',
          'coordinates on',
          '',
          '2 0  #D',
          '0 1',
          '',
          '1, 0  #e@',
          '1, 1  #q@',
          `// ${copy.eigenIntro}`,
          'focus e q',
          'checkpoint',
          '',
          'focus -',
          `// ${copy.eigenCue}`,
          'D',
          `// ${copy.eigenResult}`,
          'focus e',
        ],
      },
    ].map((lesson, index) => normalizeNotebookLesson({
      ...lesson,
      number: index + 1,
    }));
  const lessonById = new Map(lessons.map((lesson) => [lesson.id, lesson]));
  const chapters = [
    {
      id: 'vectors',
      title: copy.chapterVectorTitle,
      lessonIds: ['vector-scalar', 'vector-addition', 'linear-combination'],
    },
    {
      id: 'basis',
      title: copy.chapterBasisTitle,
      lessonIds: ['linear-independence', 'basis-coordinates'],
    },
    {
      id: 'matrices',
      title: copy.chapterMatrixTitle,
      lessonIds: ['matrix-columns', 'matrix-transform', 'determinant', 'dot-orthogonality'],
    },
    {
      id: 'systems',
      title: copy.chapterSystemTitle,
      lessonIds: ['system-two-views', 'inverse-matrix'],
    },
    {
      id: 'spaces',
      title: copy.chapterSpaceTitle,
      lessonIds: ['projection', 'column-null-space', 'eigenvector'],
    },
  ].map((chapter, chapterIndex) => ({
    ...chapter,
    numberLabel: copy.chapterNumberTemplate.replace('{n}', String(chapterIndex + 1)),
    lessons: chapter.lessonIds.map((id) => lessonById.get(id)).filter(Boolean),
  }));

  return {
    title: copy.title,
    hint: copy.hint,
    lessons,
    chapters,
  };
}
