import { buildNotebookBasicLessons } from './lessonExamples.js';
import { normalizeNotebookLesson } from './lessonScript.js';

const POSITIVE_DEFINITE_LESSON_CONTRACT = Object.freeze({
  claim: 'The matrix is positive definite because u^T A u is positive for every nonzero u.',
  evidence: 'A preserved source vector and separate Ax illustrate one energy value; a completed-square identity proves the universal claim.',
  representation: 'Graph comparison first, then a symbolic board proof.',
  operation: 'Create Ax without mutating x, then measure dot(x, Ax).',
  finalState: 'The matrix card and all-vector completed-square proof remain visible on the board.',
});

const VISUAL_COURSE_COPY = Object.freeze({
  ko: {
    title: 'Flow Math 선형대수 시각 강의',
    hint: '기초부터 응용까지 · 8강 · 25개 시각 노트',
    numberTemplate: '{n}강',
    chapters: [
      ['행렬과 가우스 소거', '연립방정식의 행·열 그림에서 출발해 소거, LU, 역행렬을 하나의 풀이 흐름으로 연결합니다.'],
      ['벡터공간과 선형변환', '선형결합에서 독립, 기저, 차원, 네 부분공간과 선형변환까지 확장합니다.'],
      ['직교성·투영·최소제곱', '내적이 만드는 직각을 투영과 최소제곱의 오차 분해로 이어 봅니다.'],
      ['행렬식', '행렬식을 넓이와 부피의 배율로 읽고, 값이 0일 때 사라지는 차원을 확인합니다.'],
      ['고유값과 고유벡터', '변환 뒤에도 남는 방향에서 시작해 대각화가 복잡한 변환을 단순화하는 방식을 봅니다.'],
      ['양의 정부호와 SVD', '양의 정부호를 에너지로 읽고 SVD를 회전·축척·회전의 세 장면으로 분해합니다.'],
      ['행렬 계산과 안정성', '조건수가 작은 입력 오차를 키우는 방식과 반복 계산이 한 방향으로 수렴하는 모습을 봅니다.'],
      ['선형계획과 게임이론', '제약식의 꼭짓점과 보수행렬의 균형을 통해 선형대수의 최적화 응용을 살펴봅니다.'],
    ],
    gaussianLabel: '가우스 소거',
    gaussianIntro: '{{A}}의 둘째 행에서 첫째 행의 2배를 빼 첫 열 아래를 0으로 만듭니다',
    gaussianCue: '이 행 연산은 기본행렬 {{E}}를 {{A}}의 왼쪽에 곱하는 것과 같습니다',
    gaussianResult: '{{U}}의 첫 열 아래가 0이 되어 뒤에서부터 해를 읽을 수 있는 **계단 구조**가 생겼습니다',
    luLabel: 'LU 분해',
    luIntro: '{{L}}은 소거 과정의 배수를 기억하고 {{U}}는 소거가 끝난 계단행렬입니다',
    luCue: '{{L}}과 {{U}}를 곱해 원래 {{A}}가 복원되는지 확인합니다',
    luResult: '{{LU}}가 {{A}}와 같습니다\n`A = LU`는 **소거 과정을 두 행렬에 저장한 식**입니다',
    leastSquaresLabel: '최소제곱',
    leastSquaresIntro: '목표 {{b}}가 방향 {{a}} 위에 없으면 가장 가까운 그림자 {{p}}를 찾습니다',
    leastSquaresCue: '오차 {{e}}를 {{p}}에 더하면 원래 목표 {{b}}가 복원됩니다',
    leastSquaresResult: '`dot({{a}}, {{e}}) = 0`입니다\n최소제곱 오차는 선택한 부분공간에 **직교**합니다',
    determinantScaleLabel: '넓이 배율',
    determinantScaleIntro: '변환 전 기저 `i`, `j`가 만드는 단위 정사각형의 넓이는 1입니다',
    determinantScaleCue: '{{A}}를 기저와 격자에 적용해 단위 정사각형을 평행사변형으로 보냅니다',
    determinantScaleResult: '같은 측정이 넓이 3으로 바뀌었습니다\n`det({{A}})=3`은 모든 넓이를 **3배**로 만든다는 뜻입니다',
    diagonalLabel: '대각화',
    diagonalIntro: '{{P}}의 열에는 {{A}}가 방향을 바꾸지 않는 고유벡터가 놓여 있습니다',
    diagonalCue: '고유기저에서는 {{D}}가 각 좌표축의 길이만 따로 바꿉니다',
    diagonalResult: '{{PD}}에 {{Pinv}}를 이어 곱하면 {{A2}}가 됩니다\n`A = PDP⁻¹`은 변환을 **기저변경·축척·복귀**로 나눈 식입니다',
    positiveLabel: '양의 정부호',
    positiveIntro: '대칭행렬 {{A}}는 모든 0이 아닌 방향에서 `xᵀAx`가 양수이면 **양의 정부호**입니다',
    positiveTransformCue: '{{x}}는 원래 위치에 보존하고, 복사한 입력에 {{A}}를 적용해 별도 결과 `Ax`를 만듭니다',
    positiveDotCue: '{{x}}와 {{Ax}}가 함께 보이는 상태에서 두 벡터를 내적해 이 방향의 에너지를 잽니다',
    positiveSample: '`dot({{x}}, {{Ax}}) = 14 > 0`입니다\n이 계산은 **한 방향의 예시**입니다',
    positiveProof: '이제 임의의 0이 아닌 벡터 `u = (a,b)`에 대해 전체 방향을 확인합니다',
    positiveResult: '`uᵀAu = 2a² + 2ab + 2b² = (a+b)² + a² + b² > 0`입니다\n따라서 {{A}}는 모든 0이 아닌 방향에서 양수인 **양의 정부호 행렬**입니다',
    svdLabel: '특이값 분해',
    svdIntro: 'SVD는 하나의 행렬을 `Vᵀ` 회전, `Σ` 축척, `U` 회전으로 나눕니다',
    svdFirst: '먼저 {{Vt}}가 입력축과 {{x}}를 회전시킵니다',
    svdSecond: '이제 {{S}}가 서로 직교한 축을 2배와 1배로 늘립니다',
    svdResult: '마지막 {{U}}가 출력 방향을 정합니다\n복잡한 변환도 **회전 → 축척 → 회전**으로 읽을 수 있습니다',
    conditionLabel: '조건수와 민감도',
    conditionIntro: '충분히 다른 두 직선은 교점 {{stable}}이 작은 변화에도 안정적입니다',
    conditionNear: '이번 두 조건은 거의 평행해서 교점이 입력 오차에 민감합니다',
    conditionResult: '상수항을 201에서 202로 1만 바꾸자 해가 `(1,1)`에서 `(2,0)`으로 크게 움직였습니다\n이 민감도를 재는 값이 **조건수**입니다',
    iterationLabel: '반복 계산',
    iterationIntro: '{{A}}를 반복 적용하면 y성분은 매번 절반이 되고 x성분은 유지됩니다',
    iterationCue: '같은 {{A}}를 다시 적용하며 {{v}}가 어느 방향으로 모이는지 봅니다',
    iterationResult: '{{v}}는 점점 x축에 가까워집니다\n반복법은 이런 **지배적인 방향**을 이용합니다',
    linearProgramLabel: '제약식과 꼭짓점',
    linearProgramIntro: '선형 부등식의 경계들은 가능한 영역을 둘러싸는 직선이 됩니다',
    linearProgramCue: '목적함수는 가능한 영역의 꼭짓점 가운데 가장 유리한 점을 고릅니다',
    linearProgramResult: '두 활성 제약의 교점 {{opt}}=`(2,2)`가 이 예의 최적 꼭짓점입니다\n선형계획은 **경계와 꼭짓점의 기하**입니다',
    gameLabel: '게임의 균형',
    gameIntro: '{{G}}는 두 전략을 골랐을 때의 보수를 기록한 행렬입니다',
    gameCue: '두 전략을 같은 확률로 섞은 {{p}}를 {{G}}에 곱합니다',
    gameResult: '{{payoff}}가 영벡터가 되어 어느 한쪽 전략에도 치우치지 않습니다\n혼합전략은 상대가 이용할 수 없는 **균형**을 만듭니다',
  },
  en: {
    title: 'Flow Math Visual Linear Algebra',
    hint: 'Foundations to applications · 8 units · 25 visual notes',
    numberTemplate: 'Unit {n}',
    chapters: [
      ['Matrices & Gaussian elimination', 'Connect row and column pictures of a system to elimination, LU, and inverse matrices.'],
      ['Vector spaces & transformations', 'Grow from linear combinations to independence, bases, the fundamental subspaces, and transformations.'],
      ['Orthogonality, projection & least squares', 'Carry the right angle created by a dot product into projection and least-squares error.'],
      ['Determinants', 'Read a determinant as an area or volume scale and watch a dimension disappear when it is zero.'],
      ['Eigenvalues & eigenvectors', 'Start with directions preserved by a transform and see how diagonalization simplifies the action.'],
      ['Positive definite matrices & SVD', 'Read positive definiteness as energy and split SVD into rotate, scale, rotate.'],
      ['Matrix computation & stability', 'See how conditioning magnifies input error and how repeated computation converges toward one direction.'],
      ['Linear programming & game theory', 'Use constraint vertices and payoff matrices to explore optimization applications.'],
    ],
    gaussianLabel: 'Gaussian elimination',
    gaussianIntro: 'Subtract twice the first row of {{A}} from the second to create a zero below the first pivot',
    gaussianCue: 'This row operation is the same as multiplying {{A}} on the left by elementary matrix {{E}}',
    gaussianResult: '{{U}} now has a zero below its first pivot, creating an **upper-triangular structure** for back substitution',
    luLabel: 'LU factorization',
    luIntro: '{{L}} remembers elimination multipliers while {{U}} is the upper-triangular result',
    luCue: 'Multiply {{L}} and {{U}} to check that they reconstruct the original {{A}}',
    luResult: '{{LU}} equals {{A}}\n`A = LU` **stores elimination in two matrices**',
    leastSquaresLabel: 'Least squares',
    leastSquaresIntro: 'When target {{b}} is not on direction {{a}}, choose its closest shadow {{p}}',
    leastSquaresCue: 'Add residual {{e}} to {{p}} to reconstruct the original target {{b}}',
    leastSquaresResult: '`dot({{a}}, {{e}}) = 0`\nA least-squares residual is **orthogonal** to the chosen subspace',
    determinantScaleLabel: 'Area scale',
    determinantScaleIntro: 'Before the transform, basis vectors `i` and `j` form a unit square of area 1',
    determinantScaleCue: 'Apply {{A}} to the basis and grid, sending the unit square to a parallelogram',
    determinantScaleResult: 'The same measurement is now area 3\n`det({{A}})=3` means every area is scaled by **3**',
    diagonalLabel: 'Diagonalization',
    diagonalIntro: 'The columns of {{P}} are eigenvectors whose directions are preserved by {{A}}',
    diagonalCue: 'In the eigenbasis, {{D}} only scales the coordinate axes independently',
    diagonalResult: 'Following {{PD}} by {{Pinv}} produces {{A2}}\n`A = PDP⁻¹` is **change basis, scale, and return**',
    positiveLabel: 'Positive definiteness',
    positiveIntro: 'A symmetric {{A}} is **positive definite** when `xᵀAx` is positive in every nonzero direction',
    positiveTransformCue: 'Keep {{x}} at its original position and apply {{A}} to a copied input to create a separate result `Ax`',
    positiveDotCue: 'With both {{x}} and {{Ax}} visible, take their dot product to measure the energy in this direction',
    positiveSample: '`dot({{x}}, {{Ax}}) = 14 > 0`\nThis calculation is **one directional example**',
    positiveProof: 'Now let `u = (a,b)` be any nonzero vector and check every direction at once',
    positiveResult: '`uᵀAu = 2a² + 2ab + 2b² = (a+b)² + a² + b² > 0`\nTherefore {{A}} is **positive definite** in every nonzero direction',
    svdLabel: 'Singular value decomposition',
    svdIntro: 'SVD splits one matrix into a `Vᵀ` rotation, a `Σ` scaling, and a `U` rotation',
    svdFirst: 'First {{Vt}} rotates the input axes and {{x}}',
    svdSecond: 'Then {{S}} stretches perpendicular axes by 2 and 1',
    svdResult: 'Finally {{U}} selects the output direction\nA complex transform becomes **rotate → scale → rotate**',
    conditionLabel: 'Conditioning & sensitivity',
    conditionIntro: 'Two clearly separated lines have an intersection {{stable}} that stays stable under small changes',
    conditionNear: 'These two conditions are nearly parallel, so their intersection is sensitive to input error',
    conditionResult: 'Changing the constant from 201 to 202 moves the solution from `(1,1)` to `(2,0)`\nThe **condition number** measures this sensitivity',
    iterationLabel: 'Iterative computation',
    iterationIntro: 'Each application of {{A}} halves the y component while preserving the x component',
    iterationCue: 'Apply the same {{A}} again and watch which direction {{v}} approaches',
    iterationResult: '{{v}} moves closer to the x-axis\nIterative methods exploit this **dominant direction**',
    linearProgramLabel: 'Constraints & vertices',
    linearProgramIntro: 'Boundaries of linear inequalities become lines enclosing a feasible region',
    linearProgramCue: 'A linear objective selects the most favorable vertex of that region',
    linearProgramResult: 'The active constraints meet at optimal vertex {{opt}}=`(2,2)`\nLinear programming is the **geometry of boundaries and vertices**',
    gameLabel: 'Game equilibrium',
    gameIntro: '{{G}} records the payoff for each pair of strategies',
    gameCue: 'Multiply {{G}} by mixed strategy {{p}}, which assigns equal probability to both choices',
    gameResult: '{{payoff}} is the zero vector, favoring neither pure strategy\nA mixed strategy creates an unexploitable **balance**',
  },
  ja: {
    title: 'Flow Math 線形代数ビジュアル講義',
    hint: '基礎から応用まで · 全8講 · 25個の可視化ノート',
    numberTemplate: '第{n}講',
    chapters: [
      ['行列とガウス消去', '連立方程式の行・列の見方から、消去、LU、逆行列までを一つの流れで結びます。'],
      ['ベクトル空間と線形変換', '線形結合から独立性、基底、基本部分空間、線形変換へ進みます。'],
      ['直交・射影・最小二乗', '内積が作る直角を、射影と最小二乗誤差へつなげます。'],
      ['行列式', '行列式を面積・体積の倍率として読み、0で次元が消える様子を見ます。'],
      ['固有値と固有ベクトル', '向きが保たれる方向から、対角化が変換を単純化する仕組みへ進みます。'],
      ['正定値行列とSVD', '正定値性をエネルギーとして読み、SVDを回転・拡大・回転に分けます。'],
      ['行列計算と安定性', '条件数が誤差を拡大する様子と、反復計算が一つの方向へ集まる様子を見ます。'],
      ['線形計画とゲーム理論', '制約の頂点と利得行列から最適化への応用を学びます。'],
    ],
    gaussianLabel: 'ガウス消去', gaussianIntro: '{{A}}の第2行から第1行の2倍を引き、第一ピボットの下を0にします', gaussianCue: 'この行操作は基本行列{{E}}を{{A}}の左から掛けることと同じです', gaussianResult: '{{U}}の第一ピボット下が0になり、後退代入できる**上三角構造**ができました',
    luLabel: 'LU分解', luIntro: '{{L}}は消去の倍率を記憶し、{{U}}は消去後の上三角行列です', luCue: '{{L}}と{{U}}を掛けて元の{{A}}が戻るか確認します', luResult: '{{LU}}は{{A}}と同じです\n`A = LU`は**消去を二つの行列に保存した式**です',
    leastSquaresLabel: '最小二乗', leastSquaresIntro: '目標{{b}}が方向{{a}}上にないとき、最も近い影{{p}}を選びます', leastSquaresCue: '残差{{e}}を{{p}}に足すと元の{{b}}が復元されます', leastSquaresResult: '`dot({{a}}, {{e}}) = 0`\n最小二乗の残差は部分空間に**直交**します',
    determinantScaleLabel: '面積の倍率', determinantScaleIntro: '変換前の基底`i`, `j`は面積1の単位正方形を作ります', determinantScaleCue: '{{A}}を基底と格子に適用し、単位正方形を平行四辺形へ送ります', determinantScaleResult: '同じ測定が面積3になりました\n`det({{A}})=3`は全ての面積を**3倍**にする意味です',
    diagonalLabel: '対角化', diagonalIntro: '{{P}}の列は{{A}}で向きが変わらない固有ベクトルです', diagonalCue: '固有基底では{{D}}が各座標軸を別々に拡大します', diagonalResult: '{{PD}}に{{Pinv}}を続けると{{A2}}になります\n`A = PDP⁻¹`は**基底変更・拡大・復帰**です',
    positiveLabel: '正定値性', positiveIntro: '対称行列{{A}}は全ての非零方向で`xᵀAx`が正なら**正定値**です', positiveTransformCue: '{{x}}は元の位置に残し、複製した入力へ{{A}}を作用させて別の結果`Ax`を作ります', positiveDotCue: '{{x}}と{{Ax}}を同時に表示し、その内積でこの方向のエネルギーを測ります', positiveSample: '`dot({{x}}, {{Ax}}) = 14 > 0`です\nこれは**一つの方向の例**です', positiveProof: '任意の非零ベクトル`u = (a,b)`について全方向をまとめて確かめます', positiveResult: '`uᵀAu = 2a² + 2ab + 2b² = (a+b)² + a² + b² > 0`です\nしたがって{{A}}は全ての非零方向で正となる**正定値行列**です',
    svdLabel: '特異値分解', svdIntro: 'SVDは行列を`Vᵀ`回転、`Σ`拡大、`U`回転に分けます', svdFirst: 'まず{{Vt}}が入力軸と{{x}}を回転します', svdSecond: '次に{{S}}が直交する軸を2倍と1倍に伸ばします', svdResult: '最後に{{U}}が出力方向を決めます\n複雑な変換も**回転 → 拡大 → 回転**で読めます',
    conditionLabel: '条件数と感度', conditionIntro: '十分に異なる二直線の交点{{stable}}は小さな変化に安定です', conditionNear: '今回は二条件がほぼ平行なので、交点が入力誤差に敏感です', conditionResult: '定数を201から202へ1だけ変えると解が`(1,1)`から`(2,0)`へ動きます\nこの感度を測るのが**条件数**です',
    iterationLabel: '反復計算', iterationIntro: '{{A}}を掛けるたびにy成分は半分になり、x成分は保たれます', iterationCue: '同じ{{A}}をもう一度掛け、{{v}}がどの方向へ集まるか見ます', iterationResult: '{{v}}はx軸へ近づきます\n反復法はこの**支配的な方向**を利用します',
    linearProgramLabel: '制約と頂点', linearProgramIntro: '線形不等式の境界は実行可能領域を囲む直線になります', linearProgramCue: '線形目的関数は領域の頂点から最も有利な点を選びます', linearProgramResult: '有効な二制約の交点{{opt}}=`(2,2)`が最適頂点です\n線形計画は**境界と頂点の幾何**です',
    gameLabel: 'ゲームの均衡', gameIntro: '{{G}}は戦略の組ごとの利得を記録した行列です', gameCue: '二戦略を同じ確率で混ぜた{{p}}を{{G}}に掛けます', gameResult: '{{payoff}}は零ベクトルで、どちらにも偏りません\n混合戦略は利用されない**均衡**を作ります',
  },
  zh: {
    title: 'Flow Math 线性代数可视化课程',
    hint: '从基础到应用 · 8课 · 25个可视化笔记',
    numberTemplate: '第{n}课',
    chapters: [
      ['矩阵与高斯消元', '把方程组的行、列图像与消元、LU分解和逆矩阵连成一条求解路线。'],
      ['向量空间与线性变换', '从线性组合扩展到无关性、基、基本子空间与线性变换。'],
      ['正交、投影与最小二乘', '把内积产生的直角延伸到投影和最小二乘误差。'],
      ['行列式', '把行列式看成面积或体积的倍率，并观察它为0时消失的维度。'],
      ['特征值与特征向量', '从保持方向的向量出发，理解对角化如何简化变换。'],
      ['正定矩阵与SVD', '把正定性理解为能量，把SVD拆成旋转、缩放、旋转。'],
      ['矩阵计算与稳定性', '观察条件数如何放大输入误差，以及迭代如何趋向一个方向。'],
      ['线性规划与博弈论', '通过约束顶点和收益矩阵理解优化应用。'],
    ],
    gaussianLabel: '高斯消元', gaussianIntro: '用{{A}}的第二行减去第一行的2倍，把第一主元下方变成0', gaussianCue: '这个行变换等价于在{{A}}左侧乘初等矩阵{{E}}', gaussianResult: '{{U}}的第一主元下方成为0，形成可回代的**上三角结构**',
    luLabel: 'LU分解', luIntro: '{{L}}记录消元倍数，{{U}}是消元后的上三角矩阵', luCue: '把{{L}}与{{U}}相乘，检查是否重建原矩阵{{A}}', luResult: '{{LU}}等于{{A}}\n`A = LU`把**消元过程存进两个矩阵**',
    leastSquaresLabel: '最小二乘', leastSquaresIntro: '当目标{{b}}不在方向{{a}}上时，选择最近的影子{{p}}', leastSquaresCue: '把残差{{e}}加到{{p}}上，就能重建目标{{b}}', leastSquaresResult: '`dot({{a}}, {{e}}) = 0`\n最小二乘残差与所选子空间**正交**',
    determinantScaleLabel: '面积倍率', determinantScaleIntro: '变换前，基向量`i`, `j`构成面积为1的单位正方形', determinantScaleCue: '把{{A}}作用于基和网格，将单位正方形送到平行四边形', determinantScaleResult: '同一测量变成面积3\n`det({{A}})=3`表示所有面积都被放大**3倍**',
    diagonalLabel: '对角化', diagonalIntro: '{{P}}的列是经过{{A}}后方向不变的特征向量', diagonalCue: '在特征基中，{{D}}只分别缩放各坐标轴', diagonalResult: '在{{PD}}后乘{{Pinv}}得到{{A2}}\n`A = PDP⁻¹`就是**换基、缩放、返回**',
    positiveLabel: '正定性', positiveIntro: '若对称矩阵{{A}}在每个非零方向上都有`xᵀAx>0`，它就是**正定矩阵**', positiveTransformCue: '保留原位置的{{x}}，把复制的输入经过{{A}}，生成独立的结果`Ax`', positiveDotCue: '让{{x}}和{{Ax}}同时可见，再用内积测量这个方向的能量', positiveSample: '`dot({{x}}, {{Ax}}) = 14 > 0`\n这只是**一个方向的例子**', positiveProof: '现在令`u = (a,b)`为任意非零向量，一次检查所有方向', positiveResult: '`uᵀAu = 2a² + 2ab + 2b² = (a+b)² + a² + b² > 0`\n因此{{A}}在每个非零方向上都为正，是**正定矩阵**',
    svdLabel: '奇异值分解', svdIntro: 'SVD把矩阵拆成`Vᵀ`旋转、`Σ`缩放和`U`旋转', svdFirst: '先由{{Vt}}旋转输入轴和{{x}}', svdSecond: '再由{{S}}把相互正交的轴拉伸2倍和1倍', svdResult: '最后{{U}}决定输出方向\n复杂变换也能读成**旋转 → 缩放 → 旋转**',
    conditionLabel: '条件数与敏感度', conditionIntro: '方向明显不同的两条直线，其交点{{stable}}对小变化较稳定', conditionNear: '这两个条件几乎平行，所以交点对输入误差很敏感', conditionResult: '常数从201变为202时，解从`(1,1)`移动到`(2,0)`\n**条件数**衡量这种敏感度',
    iterationLabel: '迭代计算', iterationIntro: '每次应用{{A}}，y分量减半而x分量保持不变', iterationCue: '再次应用同一个{{A}}，观察{{v}}趋向哪个方向', iterationResult: '{{v}}越来越接近x轴\n迭代法利用这种**主导方向**',
    linearProgramLabel: '约束与顶点', linearProgramIntro: '线性不等式的边界成为包围可行域的直线', linearProgramCue: '线性目标函数会从可行域顶点中选出最有利的点', linearProgramResult: '两个有效约束交于最优顶点{{opt}}=`(2,2)`\n线性规划是**边界与顶点的几何**',
    gameLabel: '博弈均衡', gameIntro: '{{G}}记录每对策略组合的收益', gameCue: '把两个策略等概率混合成{{p}}，再乘以{{G}}', gameResult: '{{payoff}}是零向量，不偏向任何纯策略\n混合策略产生无法被利用的**均衡**',
  },
});

function buildVisualSupplementLessons(copy) {
  return [
    {
      id: 'gaussian-elimination',
      label: copy.gaussianLabel,
      script: [
        'field board',
        '1 1  #A',
        '2 -1',
        '',
        '1 0  #E',
        '-2 1',
        `// ${copy.gaussianIntro}`,
        'mark row(A, 2)',
        'checkpoint',
        '',
        'mark -',
        `// ${copy.gaussianCue}`,
        'E * A  #U@',
        `// ${copy.gaussianResult}`,
        'mark staircase(U)',
      ],
    },
    {
      id: 'lu-factorization',
      label: copy.luLabel,
      script: [
        'field board',
        '2 1  #A',
        '4 3',
        '',
        '1 0  #L',
        '2 1',
        '',
        '2 1  #U',
        '0 1',
        `// ${copy.luIntro}`,
        'checkpoint',
        '',
        `// ${copy.luCue}`,
        'L * U  #LU@',
        `// ${copy.luResult}`,
      ],
    },
    {
      id: 'least-squares',
      label: copy.leastSquaresLabel,
      script: [
        '2d',
        'zoom 4/5',
        'coordinates on',
        '2, 1  #a@',
        'point(2, 3)  #b@',
        '14/5, 7/5  #p@',
        `// ${copy.leastSquaresIntro}`,
        'focus a p b',
        'checkpoint',
        '',
        'focus -',
        '-4/5, 8/5  #e@',
        `// ${copy.leastSquaresCue}`,
        'sum(p, e)  #rebuild@',
        'dot(a, e)  #ortho@',
        `// ${copy.leastSquaresResult}`,
        'focus a e',
      ],
    },
    {
      id: 'determinant-scale',
      label: copy.determinantScaleLabel,
      script: [
        '2d',
        'zoom 4/5',
        'grid off',
        'relative-grid on',
        'basis on',
        'coordinates off',
        '2 1  #A',
        '1 2',
        'det(i, j)  #area@',
        `// ${copy.determinantScaleIntro}`,
        'checkpoint',
        '',
        `// ${copy.determinantScaleCue}`,
        'A',
        `// ${copy.determinantScaleResult}`,
      ],
    },
    {
      id: 'diagonalization',
      label: copy.diagonalLabel,
      script: [
        'field board',
        '2 1  #A',
        '1 2',
        '',
        '1 1  #P',
        '1 -1',
        '',
        '3 0  #D',
        '0 1',
        '',
        '1/2 1/2  #Pinv',
        '1/2 -1/2',
        `// ${copy.diagonalIntro}`,
        'checkpoint',
        '',
        `// ${copy.diagonalCue}`,
        'P * D  #PD@',
        'PD * Pinv  #A2@',
        `// ${copy.diagonalResult}`,
      ],
    },
    {
      id: 'positive-definite',
      label: copy.positiveLabel,
      contract: POSITIVE_DEFINITE_LESSON_CONTRACT,
      script: [
        '2d',
        'zoom 4/5',
        'coordinates on',
        '2 1  #A',
        '1 2',
        `// ${copy.positiveIntro}`,
        'checkpoint',
        '',
        '1, 2  #x@',
        `// ${copy.positiveTransformCue}`,
        'A * x  #Ax@',
        `// ${copy.positiveDotCue}`,
        'dot(x, Ax)  #energy@',
        `// ${copy.positiveSample}`,
        'focus x Ax',
        'checkpoint',
        '',
        'focus -',
        'clear',
        'field board',
        'A +',
        `// ${copy.positiveProof}`,
        `// ${copy.positiveResult}`,
      ],
    },
    {
      id: 'svd',
      label: copy.svdLabel,
      script: [
        '2d',
        'zoom 4/5',
        'grid off',
        'relative-grid on',
        'basis on',
        'coordinates on',
        '0 1  #Vt',
        '-1 0',
        '',
        '2 0  #S',
        '0 1',
        '',
        '0 -1  #U',
        '1 0',
        '',
        '1, 1  #x@',
        `// ${copy.svdIntro}`,
        'checkpoint',
        '',
        `// ${copy.svdFirst}`,
        'Vt',
        'checkpoint',
        '',
        `// ${copy.svdSecond}`,
        'S',
        'checkpoint',
        '',
        'U',
        `// ${copy.svdResult}`,
        'focus x',
      ],
    },
    {
      id: 'condition-number',
      label: copy.conditionLabel,
      script: [
        '2d',
        'zoom 1/2',
        'coordinates on',
        'x + y = 2  #R1',
        'x - y = 0  #R2',
        'solution(R1, R2)  #stable@',
        `// ${copy.conditionIntro}`,
        'focus stable',
        'checkpoint',
        '',
        'focus -',
        'clear',
        'x + y = 2  #S1',
        '101x + 100y = 201  #S2',
        'solution(S1, S2)  #sensitive@',
        `// ${copy.conditionNear}`,
        'checkpoint',
        '',
        'clear',
        'S1 +',
        '101x + 100y = 202  #T2',
        'solution(S1, T2)  #moved@',
        `// ${copy.conditionResult}`,
        'focus moved',
      ],
    },
    {
      id: 'iterative-computation',
      label: copy.iterationLabel,
      script: [
        '2d',
        'zoom 4/5',
        'grid off',
        'relative-grid on',
        'coordinates on',
        '1 0  #A',
        '0 1/2',
        '2, 2  #v@',
        `// ${copy.iterationIntro}`,
        'checkpoint',
        '',
        'A',
        `// ${copy.iterationCue}`,
        'A',
        'A',
        `// ${copy.iterationResult}`,
        'focus v',
      ],
    },
    {
      id: 'linear-programming',
      label: copy.linearProgramLabel,
      script: [
        '2d',
        'zoom 1/2',
        'coordinates on',
        'x = 0  #X0',
        'y = 0  #Y0',
        'x + y = 4  #C1',
        '2x + y = 6  #C2',
        `// ${copy.linearProgramIntro}`,
        'focus C1 C2',
        'checkpoint',
        '',
        'focus -',
        'X0 -',
        'Y0 -',
        `// ${copy.linearProgramCue}`,
        'solution(C1, C2)  #opt@',
        `// ${copy.linearProgramResult}`,
        'focus opt',
      ],
    },
    {
      id: 'game-theory',
      label: copy.gameLabel,
      script: [
        '2d',
        'zoom 1',
        'coordinates on',
        '1 -1  #G',
        '-1 1',
        `// ${copy.gameIntro}`,
        'checkpoint',
        '',
        '1/2, 1/2  #p@',
        `// ${copy.gameCue}`,
        'G * p  #payoff@',
        `// ${copy.gameResult}`,
        'focus payoff',
      ],
    },
  ];
}

const CHAPTER_LESSONS = Object.freeze([
  [
    'system-two-views',
    'gaussian-elimination',
    'matrix-columns',
    'lu-factorization',
    'inverse-matrix',
  ],
  [
    'vector-scalar',
    'vector-addition',
    'linear-combination',
    'linear-independence',
    'basis-coordinates',
    'column-null-space',
    'matrix-transform',
  ],
  [
    'dot-orthogonality',
    'projection',
    'least-squares',
  ],
  [
    'determinant',
    'determinant-scale',
  ],
  [
    'eigenvector',
    'diagonalization',
  ],
  [
    'positive-definite',
    'svd',
  ],
  [
    'condition-number',
    'iterative-computation',
  ],
  [
    'linear-programming',
    'game-theory',
  ],
]);

export function buildVisualLinearAlgebraCourse(locale = 'ko') {
  const copy = VISUAL_COURSE_COPY[locale] ?? VISUAL_COURSE_COPY.en;
  const basics = buildNotebookBasicLessons(locale);
  const lessons = [...basics.lessons, ...buildVisualSupplementLessons(copy)]
    .map(normalizeNotebookLesson);
  const lessonById = new Map(lessons.map((lesson) => [lesson.id, lesson]));
  const chapters = CHAPTER_LESSONS.map((lessonRefs, chapterIndex) => ({
    id: `visual-${chapterIndex + 1}`,
    numberLabel: copy.numberTemplate.replace('{n}', String(chapterIndex + 1)),
    title: copy.chapters[chapterIndex][0],
    summary: copy.chapters[chapterIndex][1],
    lessons: lessonRefs
      .map((id) => lessonById.get(id) ?? null)
      .filter(Boolean),
  }));

  return {
    title: copy.title,
    hint: copy.hint,
    lessons,
    chapters,
  };
}
