import { promptSection } from './section.js';

export function buildScenePatternSections() {
  return [
    promptSection('[SCENE PATTERN LIBRARY]', [
      '- [MUST][MV-1] Matrix-vector transform-space: show `A` and `x` -> cue -> bare `A` (or `A with view ...`) -> observe the same `x` at Ax. Comparison: show `A` and `x` in identity space -> cue that the source stays put while a separate output is created -> `A * x #Ax` -> compare the still-visible `x` with `Ax`. Follow REP-1.',
      '- [MUST][SEQ-1] Sequential transforms keep one grammar for the whole chain. Transform-space tracks one `u` through bare `R`, then bare `B`; comparison creates `R * u #Ru`, then `B * Ru #BRu`, with no bare matrices.',
      '- [MUST][ROW-1] Row picture shows row equations and solver-owned solution geometry. Do not draw RHS `b` as a point/vector in x-y solution space; mention `b=(...)` as untagged algebra. The matrix declaration already shows A\'s card; use `A +` only to restore that card after `A -` or `clear`.',
      '- [MUST][COL-1] Column picture shows columns, a live sum, and optionally `point(...) #b@`. The solution tuple `x=(a,b,...)` is caption algebra, never an origin arrow. Prefer `sum(c1,c2)` followed by in-place `c1 * k`/`c2 * k` when teaching coefficient motion; name scaled copies only when original and scaled columns must coexist.',
      '- [MUST][DET-1] Determinant scale uses one live basis measurement: turn `basis on`, create `det(i,j)` in 2D or `det(i,j,k)` in 3D at identity, then keep that same measurement alive while bare `A` changes it. `dot(...)` is not determinant evidence. For `det(v1,v2)=0`, retain source vectors and the zero label; no fake collapsed face is needed.',
      '- [MUST][RANK-1] A 3D-to-2D rank drop shows disappearing volume: at identity use `basis on`, `grid off`, `relative-grid on`, and live `det(i,j,k)`; cue; then apply `A with view 2d` when the final plane benefits from a head-on view. The same volume collapses to zero. `z=0` is not a substitute.',
      '- [SHOULD][CSPACE-1] Column space prioritizes reachable outputs. Show the 3D deformation first. If a later coefficient beat only needs the two nonzero output coordinates, switch explicitly to true `2d` and use 2-component columns; switch explicitly back to `3d` before drawing the whole surviving plane as `z = 0 #ColA@`. Do not leave the story in 3D merely viewed head-on while narrating it as 2D. A zero column is either a visible origin marker when inspected or ordinary algebra when not inspected, never a hidden primary arrow. Keep rank-drop and whole-set evidence in separate beats.',
      '- [MUST][NULL-1] A nullspace claim that a nonzero input disappears ends with an actual identity-start matrix collapse of a representative nullspace vector to the origin. For a short request that claims only this representative comparison, the vectors are sufficient and CAM-2 may keep the 3D view when depth helps the disappearance read. If the narration generalizes to the whole transform—such as “A removes z, keeps x and y, and leaves a planar output”—stage `grid off` plus `relative-grid on` before the cue and use CAM-2, normally `A with view 2d` for an XY-plane result, so the environment visibly collapses and the camera finishes on the surviving output. Do not replace the matrix action with bare `2d`. Add equations and `solution(...)` only when an algebraic derivation is requested or useful.',
      '- [MUST][SOL-1] Ordinary equation declarations reveal only their lines or planes; automatic intersection geometry is off by default. When the intersection itself becomes evidence, reveal the relevant equations first, cue the solve, then write `solution(R1,R2,...) #sol@` so the engine smoothly reveals its solver-owned point, line, or plane under that alias. Never assume an undeclared automatic solution is visible, and never duplicate the native result with `point(...)` or authored coordinates.',
      '- [MUST][IND-1] Linear independence/dependence stages only the current pair; declare the contrast pair after the scene boundary, not at the beginning. In 2D, prove independence with visible nonzero `det(v1,v2)` area before concluding; different-looking directions alone are not proof. Prove dependence with visible zero determinant and, when the scalar relation is the lesson, cue the exact upcoming scale, animate `u1 * k` in place so it lands on `u2`, then state the conclusion. Name a scaled copy only when the original must remain for comparison. Write any coefficient relation with explicit multiplication, such as `` `2 * {{u1}} - {{u2}} = 0` ``.',
      '- [MUST][GAUSS-1] Gaussian elimination and elementary row-operation explanations are matrix-card algebra unless the user explicitly asks for a separate geometric interpretation. Begin with `field board`, declare coefficient matrix A and exactly one elementary matrix E just in time, state the exact row swap/scale/replacement encoded by E, cue the left multiplication, then compute `E * A #U@`. The engine recognizes a valid elementary E and automatically stages `E × A → U`, reorders/moves the operand cards, highlights source/target rows, walks across the changed row one cell at a time, draws each real cancellation strike in sequence, updates the matching calculation, and settles changed U cells in the same order. Do not manually duplicate those in-motion marks. Afterward, when the explanation makes a distinct structural claim, use BOARD-1 deliberately—for example `mark staircase(U)` while concluding that U is upper triangular—then clear it before another target. Keep A, E, and U visible for comparison; never substitute bare `E`/`A` space deformation and never write `focus U`. For several elimination steps, use one elementary matrix and one named visible product per beat (`E1 * A #U1@`, then `E2 * U1 #U2@`) so each operation remains inferable. If the request also needs row-picture geometry, use a scene boundary, switch to `field graph`, then reveal equations and `solution(...)`; do not leave graph geometry behind the board or introduce an unused hidden b.',
    ]),
  ];
}
