import { managedLocaleMessages, managedPresetLocaleNames } from '../i18n.js';
import { localeFromPathname } from './seoRoutes.js';

export const localeMessages = Object.fromEntries(
  Object.entries(managedLocaleMessages).map(([localeKey, messages]) => [
    localeKey,
    { ...messages },
  ])
);

const flowHomeLocaleMessages = {
  ko: {
    flowHomeTitle: 'Flow Math',
    flowHomeEyebrow: '시각 수학 실험실',
    flowHomeSubtitle: '수식을 쓰면 장면이 움직이고, 선과 벡터와 공간이 바로 보입니다.',
    flowHomeModuleLabel: '열 수 있는 실험',
    flowHomeLinearTitle: '선형대수',
    flowHomeLinearDescription: '행렬, 기저, 벡터, 연립방정식을 노트처럼 쓰고 애니메이션으로 확인합니다.',
    flowHomeEnter: '선형대수 열기',
    flowHomePreviewCaption: '노트가 장면을 만들고, 행렬이 그 장면을 움직입니다.',
    landingSkip: '본문으로 건너뛰기',
    landingNavAria: '홈 주요 메뉴',
    landingNavFeatures: '기능',
    landingNavWorkflow: '사용 방법',
    landingNavFaq: '자주 묻는 질문',
    landingHeaderCta: '시작하기',
    landingHeroEyebrow: '선형대수 장면 제작 도구',
    landingHeroTitleBefore: '수학의 흐름을 설계하고',
    landingHeroTitleAccent: '움직이는 장면으로 만드세요',
    landingHeroTitleAfter: '',
    landingHeroLead: 'Flow Math 프롬프트를 AI에 붙여넣고 원하는 수학 장면을 말하세요.\n생성된 결과를 가져오면 바로 애니메이션으로 재생됩니다.',
    landingHeroLeadMobile: '프롬프트를 AI에 붙여넣고 원하는 수학 장면을 말하세요.\n생성된 결과를 가져오면 애니메이션으로 재생됩니다.',
    landingPrimaryCta: 'Flow Math 시작하기',
    landingSecondaryCta: 'AI 제작 방식 보기',
    landingAssurance: '직접 구성 · AI 초안 · 타임라인 편집',
    landingPreviewAria: 'Flow Math 선형대수 실험실 미리보기 열기',
    landingPreviewFile: 'linear-map.flow',
    landingPreviewLive: '실제 Flow Math 데모',
    landingPreviewTabsAria: 'Flow Math 데모 선택',
    landingPreviewLoading: '실제 3D 장면을 불러오는 중',
    landingPreviewStudentMode: '열 관점 · 행 관점 비교를 직접 재생',
    landingPreviewReady: '장면 준비됨',
    landingPreviewNotebook: '노트북',
    landingPreviewCaption: '행렬이 면적을 2배로 늘리는 중',
    landingPreviewOpen: '이 장면 열기',
    landingExampleClose: '큰 데모 닫기',
    landingExampleMinimize: '큰 데모 최소화',
    landingExampleMaximize: '큰 데모 전체 화면',
    landingExampleRestore: '큰 데모 원래 크기',
    landingKeywordAria: 'Flow Math에서 탐구할 수 있는 선형대수 주제',
    landingKeyword1: '행렬 변환 시각화',
    landingKeyword2: '3D 벡터 시각화',
    landingKeyword3: '연립방정식 그래프',
    landingKeyword4: '행렬식과 랭크',
    landingKeyword5: '가우스 소거',
    landingKeyword6: '기저·열공간·영공간',
    landingFeatureKicker: '수학 장면 제작 도구',
    landingFeatureHeading: '직접 만들고, 필요할 때 AI로 빠르게 시작하세요',
    landingFeatureLead: 'Flow Math 문법으로 장면을 정교하게 구성할 수 있습니다. 문법이 낯설다면 제작 프롬프트로 AI 초안을 만든 뒤, 타임라인에서 수식·그래프·카메라·타이밍을 직접 편집하세요.',
    landingFeature1Title: '두 가지 제작 경로',
    landingFeature1Body: '노트북 문법으로 처음부터 직접 작성하거나, 제작 프롬프트를 익숙한 AI에 붙여 초안을 만드세요. 어느 경로든 결과는 같은 편집 가능한 Flow Math 장면이 됩니다.',
    landingFeature1BodyMobile: '노트북 문법으로 직접 쓰거나, 제작 프롬프트로 AI 초안을 만드세요. 결과는 같은 편집 가능한 장면입니다.',
    landingFeaturePromptSource: '제작 프롬프트 복사',
    landingFeaturePromptResult: 'AI 초안 → 장면',
    landingFeature2Title: '시간을 되감는 타임라인',
    landingFeature2Body: '재생, 일시정지, 구간 이동으로 변환 전후를 비교하고 놓친 단계를 다시 확인합니다.',
    landingFeature2BodyMobile: '재생·정지·구간 이동으로 변화 전후와 각 단계를 다시 봅니다.',
    landingFeature3Title: '2D와 3D를 한 흐름으로',
    landingFeature3Body: '직선과 평면, 벡터와 기저, 면적과 부피의 변화를 알맞은 시점에서 탐구합니다.',
    landingFeature3BodyMobile: '직선·평면·벡터·기저·면적·부피를 2D와 3D에서 살펴봅니다.',
    landingFeature4Title: '계산판과 그래프 동기화',
    landingFeature4Body: '식의 전개와 공간의 변화를 함께 보여줘 기호 계산이 무엇을 뜻하는지 연결합니다.',
    landingFeature4BodyMobile: '수식 전개와 공간 변화를 함께 보여 계산이 무엇을 바꾸는지 연결합니다.',
    landingFeature5Title: '애니메이션 링크 공유',
    landingFeature5Body: '작성한 노트와 재생 상태를 링크로 공유해 같은 설명 장면을 학생이나 동료에게 전달합니다.',
    landingFeature5BodyMobile: '노트와 재생 상태를 링크로 공유해 같은 장면을 그대로 전달합니다.',
    landingFeature6Title: '설명·캡션·체크포인트',
    landingFeature6Body: '중요한 변화마다 짧은 설명과 멈춤 지점을 두어 장면만 보고도 핵심을 따라갈 수 있습니다.',
    landingFeature6BodyMobile: '설명·캡션·체크포인트로 중요한 변화만 따라가게 합니다.',
    landingAudienceKicker: '누가 사용하나요',
    landingAudienceHeading: '공식을 외우기 전에 구조를 보고 싶은 사람',
    landingAudience1Title: '대학생·독학 학습자',
    landingAudience1Body: '행렬식, 고유한 방향, 랭크와 영공간처럼 종이 위에서 추상적인 개념을 공간 변화로 확인합니다.',
    landingAudience2Title: '교수자·튜터',
    landingAudience2Body: '판서 흐름을 재생 가능한 시각 강의로 만들고, 수업 뒤에도 같은 장면을 링크로 공유합니다.',
    landingAudience3Title: '개발·데이터·ML 학습자',
    landingAudience3Body: '코드에서 쓰는 벡터와 행렬 연산이 실제 공간에 어떤 영향을 주는지 직관을 쌓습니다.',
    landingWorkflowKicker: '빠른 시작 경로 · AI',
    landingWorkflowHeading: '복사하고, AI와 만들고, 바로 재생하세요',
    landingWorkflowLead: '앱 안에서 특정 AI를 고르는 방식이 아닙니다. 제작 프롬프트를 복사해 내가 쓰는 AI에서 초안과 수정을 만들고, 완성된 스크립트만 Flow Math에 붙여넣습니다.',
    landingStep1Title: '제작 프롬프트 복사',
    landingStep1Body: '실험실의 ‘AI로 만들기’를 열고 Flow Math 문법과 연출 규칙이 담긴 제작 프롬프트를 복사합니다.',
    landingStep2Title: '내 AI에 장면 요청',
    landingStep2Body: '프롬프트를 사용하는 AI에 붙여넣고 개념, 문제, 수식이나 원하는 장면을 말합니다. 결과를 보며 수정도 요청합니다.',
    landingStep3Title: '스크립트 붙여넣고 재생',
    landingStep3Body: 'AI가 만든 전체 노트북 스크립트를 Flow Math에 붙여넣고, 2D·3D 애니메이션을 재생·스크럽·공유합니다.',
    landingFaqKicker: 'FAQ',
    landingFaqHeading: 'Flow Math를 시작하기 전에',
    landingFaq1Question: 'Flow Math는 어떤 도구인가요?',
    landingFaq1Answer: 'Flow Math는 제작 프롬프트를 평소 사용하는 AI에 복사해 선형대수 노트북 스크립트를 만들고, 그 결과를 2D·3D 애니메이션으로 재생·수정·공유하는 브라우저 기반 실험실입니다.',
    landingFaq2Question: '일반 선형대수 계산기와 무엇이 다른가요?',
    landingFaq2Answer: '일반 계산기가 최종 숫자나 해를 중심으로 보여준다면, Flow Math는 선언과 연산의 순서를 장면으로 만들고 타임라인에서 변환 과정을 재생·정지·되돌릴 수 있게 합니다.',
    landingFaq3Question: '어떤 선형대수 주제를 시각화할 수 있나요?',
    landingFaq3Answer: '행렬 변환, 벡터와 기저, 내적, 행렬식, 면적과 부피, 직선·평면·연립방정식, 랭크와 영공간, 행 연산을 한 노트북 흐름 안에서 다룰 수 있습니다.',
    landingFaq4Question: '내가 만든 장면을 다른 사람과 공유할 수 있나요?',
    landingFaq4Answer: '네. 노트와 애니메이션 상태를 담은 공유 링크를 만들어 학생, 동료 또는 스터디 구성원이 같은 장면을 열어보게 할 수 있습니다.',
    landingFaq5Question: '프로그램을 설치해야 하나요?',
    landingFaq5Answer: '별도 프로그램 설치 없이 최신 웹 브라우저에서 사용할 수 있습니다. 3D 장면과 노트북을 함께 볼 때는 화면이 넓은 환경이 가장 편합니다.',
    landingFinalKicker: '설계에서 장면으로',
    landingFinalHeading: '첫 선형대수 장면을 원하는 방식으로 만드세요',
    landingFinalLead: '직접 구성하거나 AI로 초안을 만든 뒤, Flow Math에서 세밀하게 편집하고 재생하세요.',
    landingFinalCta: 'Flow Math 시작하기',
    landingFooterTagline: 'Animation-first linear algebra lab',
    landingFooterReference: '선형대수 참고 교재',
    flowHomeLoginTitle: 'Flow Math 로그인',
    flowHomeLoginGoogle: 'Google로 계속하기',
    flowHomeEmailPlaceholder: '이메일 주소',
    flowHomeEmailLogin: '이메일로 로그인',
    flowHomeEmailSignup: '계정 만들기',
    flowHomeLoginCancel: '닫기',
    flowHomeLoginEmailRequired: '이메일을 입력해주세요.',
    flowHomeLoginEmailExists: '이미 가입된 이메일입니다.',
    flowHomeLoginEmailMissing: '가입되지 않은 이메일입니다.',
    flowHomeLoginFailed: '로그인 처리에 실패했습니다.',
  },
  en: {
    flowHomeTitle: 'Flow Math',
    flowHomeEyebrow: 'Visual math lab',
    flowHomeSubtitle: 'Write math and watch lines, vectors, and spaces move as a scene.',
    flowHomeModuleLabel: 'Available lab',
    flowHomeLinearTitle: 'Linear Algebra',
    flowHomeLinearDescription: 'Write matrices, bases, vectors, and systems like a notebook, then scrub the animation.',
    flowHomeEnter: 'Open Linear Algebra',
    flowHomePreviewCaption: 'The notebook builds the scene; matrices animate the change.',
    landingSkip: 'Skip to main content',
    landingNavAria: 'Home navigation',
    landingNavFeatures: 'Features',
    landingNavWorkflow: 'How it works',
    landingNavFaq: 'FAQ',
    landingHeaderCta: 'Get started',
    landingHeroEyebrow: 'Build directly, or start faster with AI',
    landingHeroTitleBefore: 'Design the flow of mathematics.',
    landingHeroTitleAccent: 'Turn it into a moving scene.',
    landingHeroTitleAfter: '',
    landingHeroLead: 'Build scenes directly or generate a first draft with AI. Freely edit equations, graphs, 2D and 3D direction, and timing on the timeline.',
    landingHeroLeadMobile: 'Build scenes directly or generate a first draft with AI. Freely edit equations, graphs, 2D and 3D direction, and timing on the timeline.',
    landingPrimaryCta: 'Start Flow Math',
    landingSecondaryCta: 'See the AI workflow',
    landingAssurance: 'Direct authoring · AI drafts · Timeline editing',
    landingPreviewAria: 'Open the Flow Math linear algebra lab preview',
    landingPreviewFile: 'linear-map.flow',
    landingPreviewLive: 'Live Flow Math demo',
    landingPreviewTabsAria: 'Choose a Flow Math demo',
    landingPreviewLoading: 'Loading the live 3D scene',
    landingPreviewStudentMode: 'Replay the column view · row view comparison',
    landingPreviewReady: 'Scene ready',
    landingPreviewNotebook: 'Notebook',
    landingPreviewCaption: 'The matrix is doubling the area',
    landingPreviewOpen: 'Open this scene',
    landingExampleClose: 'Close full demo',
    landingExampleMinimize: 'Minimize demo',
    landingExampleMaximize: 'Maximize demo',
    landingExampleRestore: 'Restore demo size',
    landingKeywordAria: 'Linear algebra topics you can explore in Flow Math',
    landingKeyword1: 'Matrix transformation visualizer',
    landingKeyword2: '3D vector visualizer',
    landingKeyword3: 'Systems of equations graph',
    landingKeyword4: 'Determinant and rank',
    landingKeyword5: 'Gaussian elimination',
    landingKeyword6: 'Basis, column space, null space',
    landingFeatureKicker: 'A tool for mathematical scenes',
    landingFeatureHeading: 'Build directly, and use AI when you want a faster start',
    landingFeatureLead: 'Use Flow Math syntax to compose precise scenes. If the syntax is unfamiliar, generate an AI draft with the authoring prompt, then edit the equations, graphs, camera, and timing yourself.',
    landingFeature1Title: 'Two authoring paths',
    landingFeature1Body: 'Write the notebook syntax yourself or paste the authoring prompt into the AI you already use for a first draft. Either path produces the same editable Flow Math scene.',
    landingFeature1BodyMobile: 'Write in notebook syntax or use the authoring prompt for an AI draft. Both produce the same editable scene.',
    landingFeaturePromptSource: 'Copy authoring prompt',
    landingFeaturePromptResult: 'AI draft → scene',
    landingFeature2Title: 'A timeline you can rewind',
    landingFeature2Body: 'Play, pause, and scrub to compare before and after states or revisit a step you missed.',
    landingFeature2BodyMobile: 'Play, pause, and move between segments to compare each stage.',
    landingFeature3Title: 'One flow across 2D and 3D',
    landingFeature3Body: 'Explore lines, planes, vectors, bases, area, and volume from the view that makes each idea clear.',
    landingFeature3BodyMobile: 'Explore lines, planes, vectors, bases, area, and volume in 2D and 3D.',
    landingFeature4Title: 'Algebra and graph stay in sync',
    landingFeature4Body: 'Follow the symbolic work beside the spatial change so an operation never becomes a disconnected formula.',
    landingFeature4BodyMobile: 'See symbolic steps and spatial change together.',
    landingFeature5Title: 'Share an animation link',
    landingFeature5Body: 'Share the notebook and its playback state so students or teammates can open the same explanation scene.',
    landingFeature5BodyMobile: 'Share the notebook and playback state as one scene link.',
    landingFeature6Title: 'Captions and checkpoints',
    landingFeature6Body: 'Short explanations and deliberate pauses make the central evidence readable without dense interface text.',
    landingFeature6BodyMobile: 'Use captions and checkpoints to follow the important changes.',
    landingAudienceKicker: 'Who it is for',
    landingAudienceHeading: 'For anyone who wants to see structure before memorizing formulas',
    landingAudience1Title: 'Students and self-learners',
    landingAudience1Body: 'Turn abstract ideas such as determinants, rank, and null space into visible changes in space.',
    landingAudience2Title: 'Educators and tutors',
    landingAudience2Body: 'Turn a board-work sequence into a replayable visual lesson and share the same scene after class.',
    landingAudience3Title: 'Developers, data, and ML learners',
    landingAudience3Body: 'Build intuition for what vector and matrix operations in code actually do to a space.',
    landingWorkflowKicker: 'Fast-start path · AI',
    landingWorkflowHeading: 'Copy it, build with your AI, and press play',
    landingWorkflowLead: 'You do not choose a built-in AI model. Copy the authoring prompt, draft and revise with the AI you already use, then paste only the finished script into Flow Math.',
    landingStep1Title: 'Copy the authoring prompt',
    landingStep1Body: 'Open “Create with AI” in the lab and copy the production prompt containing Flow Math syntax and directing rules.',
    landingStep2Title: 'Ask your AI for a scene',
    landingStep2Body: 'Paste the prompt into your AI and describe a concept, problem, equation, or visual direction. Ask for revisions after reviewing the draft.',
    landingStep3Title: 'Paste the script and play',
    landingStep3Body: 'Paste the complete notebook script into Flow Math, then play, scrub, and share the 2D or 3D animation.',
    landingFaqKicker: 'FAQ',
    landingFaqHeading: 'Before you start with Flow Math',
    landingFaq1Question: 'What is Flow Math?',
    landingFaq1Answer: 'Flow Math is a browser-based lab where you copy an authoring prompt into the AI you already use, create a linear algebra notebook script, and replay, refine, or share the result as a 2D or 3D animation.',
    landingFaq2Question: 'How is it different from a linear algebra calculator?',
    landingFaq2Answer: 'A calculator usually emphasizes a final number or solution. Flow Math turns the order of declarations and operations into scenes, then lets you play, pause, and rewind the transformation process.',
    landingFaq3Question: 'Which linear algebra topics can I visualize?',
    landingFaq3Answer: 'You can explore matrix transformations, vectors and bases, dot products, determinants, area and volume, lines, planes, systems, rank, null space, and row operations in one notebook flow.',
    landingFaq4Question: 'Can I share a scene I create?',
    landingFaq4Answer: 'Yes. You can create a share link that carries the notebook and animation state so a student, teammate, or study group can open the same scene.',
    landingFaq5Question: 'Do I need to install anything?',
    landingFaq5Answer: 'No separate program is required. Flow Math runs in a modern web browser, with a larger screen recommended when viewing the notebook and 3D scene together.',
    landingFinalKicker: 'From design to scene',
    landingFinalHeading: 'Build your first linear algebra scene your way',
    landingFinalLead: 'Compose it directly or begin with an AI draft, then refine and replay it in Flow Math.',
    landingFinalCta: 'Start Flow Math',
    landingFooterTagline: 'Animation-first linear algebra lab',
    landingFooterReference: 'Linear algebra reference',
    flowHomeLoginTitle: 'Sign in to Flow Math',
    flowHomeLoginGoogle: 'Continue with Google',
    flowHomeEmailPlaceholder: 'Email address',
    flowHomeEmailLogin: 'Sign in with email',
    flowHomeEmailSignup: 'Sign up',
    flowHomeLoginCancel: 'Close',
    flowHomeLoginEmailRequired: 'Enter an email address.',
    flowHomeLoginEmailExists: 'That email is already signed up.',
    flowHomeLoginEmailMissing: 'That email is not signed up yet.',
    flowHomeLoginFailed: 'Sign-in failed.',
  },
  ja: {
    flowHomeTitle: 'Flow Math',
    flowHomeEyebrow: '視覚数学ラボ',
    flowHomeSubtitle: '数式を書くと、線・ベクトル・空間がそのまま動く場面になります。',
    flowHomeModuleLabel: '利用できるラボ',
    flowHomeLinearTitle: '線形代数',
    flowHomeLinearDescription: '行列、基底、ベクトル、連立方程式をノートのように書き、アニメーションで確認します。',
    flowHomeEnter: '線形代数を開く',
    flowHomePreviewCaption: 'ノートが場面を作り、行列が変化を動かします。',
    landingSkip: '本文へ移動',
    landingNavAria: 'ホームナビゲーション',
    landingNavFeatures: '機能',
    landingNavWorkflow: '使い方',
    landingNavFaq: 'よくある質問',
    landingHeaderCta: '始める',
    landingHeroEyebrow: '直接作る、またはAIですばやく',
    landingHeroTitleBefore: '数学の流れを設計し',
    landingHeroTitleAccent: '動く場面にしましょう',
    landingHeroTitleAfter: '',
    landingHeroLead: '場面を直接構成することも、AIで下書きを作ることもできます。数式・グラフ・2D・3Dの演出をタイムラインで自由に編集できます。',
    landingHeroLeadMobile: '場面を直接構成することも、AIで下書きを作ることもできます。数式・グラフ・2D・3Dの演出をタイムラインで自由に編集できます。',
    landingPrimaryCta: 'Flow Mathを始める',
    landingSecondaryCta: 'AI制作の流れを見る',
    landingAssurance: '直接制作 · AI下書き · タイムライン編集',
    landingPreviewAria: 'Flow Math 線形代数ラボのプレビューを開く',
    landingPreviewFile: 'linear-map.flow',
    landingPreviewLive: 'Flow Math ライブデモ',
    landingPreviewTabsAria: 'Flow Math デモを選択',
    landingPreviewLoading: '実際の3Dシーンを読み込み中',
    landingPreviewStudentMode: '列の見方 · 行の見方を比較再生',
    landingPreviewReady: '場面の準備完了',
    landingPreviewNotebook: 'ノートブック',
    landingPreviewCaption: '行列が面積を2倍に変換中',
    landingPreviewOpen: 'この場面を開く',
    landingExampleClose: '大きなデモを閉じる',
    landingExampleMinimize: 'デモを最小化',
    landingExampleMaximize: 'デモを最大化',
    landingExampleRestore: 'デモを元のサイズに戻す',
    landingKeywordAria: 'Flow Math で学べる線形代数のテーマ',
    landingKeyword1: '行列変換の可視化',
    landingKeyword2: '3Dベクトル可視化',
    landingKeyword3: '連立方程式グラフ',
    landingKeyword4: '行列式とランク',
    landingKeyword5: 'ガウス消去法',
    landingKeyword6: '基底・列空間・零空間',
    landingFeatureKicker: '数学場面の制作ツール',
    landingFeatureHeading: '直接作り、必要なときはAIですばやく始める',
    landingFeatureLead: 'Flow Mathの文法で場面を精密に構成できます。文法に慣れていなければ、制作プロンプトでAIの下書きを作り、数式・グラフ・カメラ・タイミングを自分で編集できます。',
    landingFeature1Title: '二つの制作方法',
    landingFeature1Body: 'ノートブック文法を直接書くか、普段使うAIに制作プロンプトを貼って下書きを作ります。どちらも同じ編集可能なFlow Math場面になります。',
    landingFeature1BodyMobile: 'ノートブック文法で直接書くか、制作プロンプトでAIの下書きを作ります。どちらも同じ編集可能な場面になります。',
    landingFeaturePromptSource: '制作プロンプトをコピー',
    landingFeaturePromptResult: 'AI初稿 → 場面',
    landingFeature2Title: '巻き戻せるタイムライン',
    landingFeature2Body: '再生、一時停止、スクラブで変換前後を比較し、見逃した段階を確認できます。',
    landingFeature2BodyMobile: '再生・停止・区間移動で変化の前後と各段階を見直せます。',
    landingFeature3Title: '2Dと3Dを一つの流れで',
    landingFeature3Body: '直線、平面、ベクトル、基底、面積、体積を理解しやすい視点で探究します。',
    landingFeature3BodyMobile: '直線・平面・ベクトル・基底・面積・体積を2Dと3Dで確認します。',
    landingFeature4Title: '計算とグラフを同期',
    landingFeature4Body: '式の展開と空間の変化を並べて、記号の操作が何を意味するか結びつけます。',
    landingFeature4BodyMobile: '数式の展開と空間の変化を一緒に示します。',
    landingFeature5Title: 'アニメーションをリンク共有',
    landingFeature5Body: 'ノートと再生状態を共有し、学生や仲間が同じ説明場面を開けます。',
    landingFeature5BodyMobile: 'ノートと再生状態を一つの場面リンクで共有します。',
    landingFeature6Title: '説明・字幕・チェックポイント',
    landingFeature6Body: '重要な変化に短い説明と停止点を置き、場面だけでも要点を追えるようにします。',
    landingFeature6BodyMobile: '字幕とチェックポイントで重要な変化だけを追えます。',
    landingAudienceKicker: '対象ユーザー',
    landingAudienceHeading: '公式を覚える前に構造を見たい人へ',
    landingAudience1Title: '大学生・独学者',
    landingAudience1Body: '行列式、ランク、零空間など抽象的な概念を空間の変化として確認します。',
    landingAudience2Title: '教員・チューター',
    landingAudience2Body: '板書の流れを再生可能な視覚授業に変え、授業後も同じ場面を共有します。',
    landingAudience3Title: '開発・データ・ML学習者',
    landingAudience3Body: 'コード中のベクトルと行列演算が空間に及ぼす影響を直感的に理解します。',
    landingWorkflowKicker: 'すばやく始める方法 · AI',
    landingWorkflowHeading: 'コピーして、AIと作り、すぐ再生',
    landingWorkflowLead: 'アプリ内で特定のAIを選ぶ方式ではありません。制作プロンプトをコピーし、普段使うAIで下書きと修正を行い、完成したスクリプトだけをFlow Mathに貼り付けます。',
    landingStep1Title: '制作プロンプトをコピー',
    landingStep1Body: 'ラボの「AIで作る」を開き、Flow Mathの文法と演出ルールを含む制作プロンプトをコピーします。',
    landingStep2Title: 'AIに場面を依頼',
    landingStep2Body: 'プロンプトを普段使うAIに貼り、概念・問題・数式・演出を伝えます。初稿を見ながら修正も依頼できます。',
    landingStep3Title: '貼り付けて再生',
    landingStep3Body: 'AIが作った完全なノートブックスクリプトをFlow Mathに貼り、2D・3Dアニメーションを再生・スクラブ・共有します。',
    landingFaqKicker: 'FAQ',
    landingFaqHeading: 'Flow Math を始める前に',
    landingFaq1Question: 'Flow Math はどんなツールですか？',
    landingFaq1Answer: 'Flow Mathは制作プロンプトを普段使うAIにコピーして線形代数のノートブックスクリプトを作り、その結果を2D・3Dアニメーションとして再生・修正・共有するブラウザ型ラボです。',
    landingFaq2Question: '一般的な線形代数計算機との違いは？',
    landingFaq2Answer: '最終的な数値だけでなく、宣言と演算の順序を場面にし、タイムラインで変換過程を再生・停止・巻き戻せます。',
    landingFaq3Question: 'どのテーマを可視化できますか？',
    landingFaq3Answer: '行列変換、ベクトルと基底、内積、行列式、面積と体積、直線・平面・連立方程式、ランク、零空間、行基本変形を扱えます。',
    landingFaq4Question: '作った場面を共有できますか？',
    landingFaq4Answer: 'はい。ノートとアニメーション状態を含むリンクを作り、学生や仲間が同じ場面を開けます。',
    landingFaq5Question: 'インストールは必要ですか？',
    landingFaq5Answer: '別のプログラムは不要で、最新のウェブブラウザで使えます。ノートと3D場面を一緒に見るには広い画面がおすすめです。',
    landingFinalKicker: '設計から場面へ',
    landingFinalHeading: '自分に合う方法で最初の線形代数場面を作る',
    landingFinalLead: '直接構成するかAIの下書きから始め、Flow Mathで細かく編集して再生してください。',
    landingFinalCta: 'Flow Mathを始める',
    landingFooterTagline: 'Animation-first linear algebra lab',
    landingFooterReference: '線形代数の参考教材',
    flowHomeLoginTitle: 'Flow Math にログイン',
    flowHomeLoginGoogle: 'Googleで続ける',
    flowHomeEmailPlaceholder: 'メールアドレス',
    flowHomeEmailLogin: 'メールでログイン',
    flowHomeEmailSignup: 'アカウントを作成',
    flowHomeLoginCancel: '閉じる',
    flowHomeLoginEmailRequired: 'メールアドレスを入力してください。',
    flowHomeLoginEmailExists: 'このメールはすでに登録されています。',
    flowHomeLoginEmailMissing: 'このメールはまだ登録されていません。',
    flowHomeLoginFailed: 'ログインに失敗しました。',
  },
  zh: {
    flowHomeTitle: 'Flow Math',
    flowHomeEyebrow: '可视化数学实验室',
    flowHomeSubtitle: '写下数学，直线、向量和空间会立刻变成可观察的动画。',
    flowHomeModuleLabel: '可进入的实验',
    flowHomeLinearTitle: '线性代数',
    flowHomeLinearDescription: '像写笔记一样输入矩阵、基、向量和方程组，再用动画观察变化。',
    flowHomeEnter: '打开线性代数',
    flowHomePreviewCaption: '笔记生成场景，矩阵推动变化。',
    landingSkip: '跳到正文',
    landingNavAria: '主页导航',
    landingNavFeatures: '功能',
    landingNavWorkflow: '使用方式',
    landingNavFaq: '常见问题',
    landingHeaderCta: '开始使用',
    landingHeroEyebrow: '直接制作，或用 AI 快速开始',
    landingHeroTitleBefore: '设计数学的流动',
    landingHeroTitleAccent: '把它变成会动的场景',
    landingHeroTitleAfter: '',
    landingHeroLead: '你可以直接构建场景，也可以用 AI 生成初稿。在时间轴中自由编辑公式、图形、2D 与 3D 演出。',
    landingHeroLeadMobile: '你可以直接构建场景，也可以用 AI 生成初稿。在时间轴中自由编辑公式、图形、2D 与 3D 演出。',
    landingPrimaryCta: '开始使用 Flow Math',
    landingSecondaryCta: '查看 AI 制作流程',
    landingAssurance: '直接制作 · AI 初稿 · 时间轴编辑',
    landingPreviewAria: '打开 Flow Math 线性代数实验室预览',
    landingPreviewFile: 'linear-map.flow',
    landingPreviewLive: 'Flow Math 实时演示',
    landingPreviewTabsAria: '选择 Flow Math 演示',
    landingPreviewLoading: '正在加载真实的 3D 场景',
    landingPreviewStudentMode: '交互播放列视角 · 行视角对比',
    landingPreviewReady: '场景已就绪',
    landingPreviewNotebook: '笔记本',
    landingPreviewCaption: '矩阵正在把面积放大到2倍',
    landingPreviewOpen: '打开此场景',
    landingExampleClose: '关闭大型演示',
    landingExampleMinimize: '最小化演示',
    landingExampleMaximize: '最大化演示',
    landingExampleRestore: '恢复演示大小',
    landingKeywordAria: '可在 Flow Math 中探索的线性代数主题',
    landingKeyword1: '矩阵变换可视化',
    landingKeyword2: '3D向量可视化',
    landingKeyword3: '方程组图像',
    landingKeyword4: '行列式与秩',
    landingKeyword5: '高斯消元',
    landingKeyword6: '基·列空间·零空间',
    landingFeatureKicker: '数学场景制作工具',
    landingFeatureHeading: '直接制作，需要时再用 AI 快速开始',
    landingFeatureLead: '使用 Flow Math 语法精确构建场景。如果还不熟悉语法，可通过制作提示词生成 AI 初稿，再亲自编辑公式、图形、镜头与节奏。',
    landingFeature1Title: '两种制作路径',
    landingFeature1Body: '你可以从头编写笔记语法，也可以把制作提示词交给常用 AI 生成初稿。两种路径最终都会得到同样可编辑的 Flow Math 场景。',
    landingFeature1BodyMobile: '直接编写笔记语法，或用制作提示词生成 AI 初稿。两种方式都会得到同样可编辑的场景。',
    landingFeaturePromptSource: '复制制作提示词',
    landingFeaturePromptResult: 'AI 初稿 → 场景',
    landingFeature2Title: '可倒回的时间轴',
    landingFeature2Body: '播放、暂停和拖动进度，对比变换前后并重新查看错过的步骤。',
    landingFeature2BodyMobile: '通过播放、暂停和区间跳转比较每个阶段。',
    landingFeature3Title: '贯通2D与3D',
    landingFeature3Body: '用合适的视角探索直线、平面、向量、基、面积和体积。',
    landingFeature3BodyMobile: '在 2D 与 3D 中查看直线、平面、向量、基、面积和体积。',
    landingFeature4Title: '计算与图像同步',
    landingFeature4Body: '把符号推导和空间变化并排展示，理解每个运算的几何含义。',
    landingFeature4BodyMobile: '同时呈现公式推导与空间变化。',
    landingFeature5Title: '分享动画链接',
    landingFeature5Body: '通过链接分享笔记和播放状态，让同学或伙伴打开同一个讲解场景。',
    landingFeature5BodyMobile: '把笔记和播放状态作为一个场景链接分享。',
    landingFeature6Title: '说明、字幕与检查点',
    landingFeature6Body: '在关键变化处加入短说明和停顿点，只看场景也能跟上重点。',
    landingFeature6BodyMobile: '用字幕和检查点跟随重要变化。',
    landingAudienceKicker: '适合谁',
    landingAudienceHeading: '适合想在记公式前先看清结构的人',
    landingAudience1Title: '大学生与自学者',
    landingAudience1Body: '把行列式、秩、零空间等抽象概念转化为空间中的可见变化。',
    landingAudience2Title: '教师与辅导者',
    landingAudience2Body: '把板书过程做成可回放的可视课程，并在课后分享同一场景。',
    landingAudience3Title: '开发、数据与机器学习者',
    landingAudience3Body: '直观理解代码中的向量和矩阵运算会怎样改变空间。',
    landingWorkflowKicker: '快速开始路径 · AI',
    landingWorkflowHeading: '复制、用 AI 制作，然后直接播放',
    landingWorkflowLead: '这不是在应用内选择某个固定 AI。复制制作提示词，在你常用的 AI 中完成初稿和修改，再把最终脚本粘贴到 Flow Math。',
    landingStep1Title: '复制制作提示词',
    landingStep1Body: '打开实验室中的“用 AI 创建”，复制包含 Flow Math 语法与演出规则的制作提示词。',
    landingStep2Title: '向你的 AI 描述场景',
    landingStep2Body: '将提示词粘贴到常用 AI，再说明概念、题目、公式或场景要求。查看初稿后可继续要求修改。',
    landingStep3Title: '粘贴脚本并播放',
    landingStep3Body: '把 AI 生成的完整笔记脚本粘贴到 Flow Math，再播放、拖动和分享 2D 或 3D 动画。',
    landingFaqKicker: 'FAQ',
    landingFaqHeading: '开始使用 Flow Math 之前',
    landingFaq1Question: 'Flow Math 是什么工具？',
    landingFaq1Answer: 'Flow Math 是一个浏览器实验室：把制作提示词复制到你常用的 AI，生成线性代数笔记脚本，再将结果以 2D 或 3D 动画播放、修改和分享。',
    landingFaq2Question: '它与普通线性代数计算器有什么不同？',
    landingFaq2Answer: '普通计算器侧重最终数字或解；Flow Math 把声明与运算顺序做成场景，可在时间轴上播放、暂停和倒回变换过程。',
    landingFaq3Question: '可以可视化哪些主题？',
    landingFaq3Answer: '可探索矩阵变换、向量与基、内积、行列式、面积与体积、直线、平面、方程组、秩、零空间和行变换。',
    landingFaq4Question: '可以分享我创建的场景吗？',
    landingFaq4Answer: '可以。分享链接会带上笔记与动画状态，让同学、同事或学习小组打开同一个场景。',
    landingFaq5Question: '需要安装程序吗？',
    landingFaq5Answer: '不需要单独安装，在现代网页浏览器中即可使用。同时查看笔记与3D场景时，较大的屏幕体验更好。',
    landingFinalKicker: '从设计到场景',
    landingFinalHeading: '用适合你的方式制作第一个线性代数场景',
    landingFinalLead: '直接构建或从 AI 初稿开始，再在 Flow Math 中细致编辑并播放。',
    landingFinalCta: '开始使用 Flow Math',
    landingFooterTagline: 'Animation-first linear algebra lab',
    landingFooterReference: '线性代数参考教材',
    flowHomeLoginTitle: '登录 Flow Math',
    flowHomeLoginGoogle: '使用 Google 继续',
    flowHomeEmailPlaceholder: '电子邮箱',
    flowHomeEmailLogin: '邮箱登录',
    flowHomeEmailSignup: '创建账户',
    flowHomeLoginCancel: '关闭',
    flowHomeLoginEmailRequired: '请输入邮箱。',
    flowHomeLoginEmailExists: '该邮箱已注册。',
    flowHomeLoginEmailMissing: '该邮箱尚未注册。',
    flowHomeLoginFailed: '登录失败。',
  },
};

const flowHomePasswordLocaleMessages = {
  ko: {
    flowHomePasswordPlaceholder: '비밀번호',
    flowHomeLoginPasswordRequired: '비밀번호를 입력해주세요.',
    flowHomeLoginPasswordShort: '비밀번호는 8자 이상이어야 합니다.',
    flowHomeLoginPasswordInvalid: '비밀번호가 맞지 않습니다.',
    flowAuthModeLabel: '로그인 또는 회원가입',
    flowAuthLoginTab: '로그인',
    flowAuthSignupTab: '회원가입',
    flowAuthLoginTitle: '다시 만나서 반가워요',
    flowAuthSignupTitle: 'Flow Math 시작하기',
    flowAuthLoginLead: '계정으로 들어가 선형대수 실험실을 계속 사용하세요.',
    flowAuthSignupLead: '이메일과 비밀번호만으로 바로 계정을 만들 수 있어요.',
    flowAuthOrEmail: '또는 이메일로',
    flowAuthEmailLabel: '이메일',
    flowAuthPasswordLabel: '비밀번호',
    flowAuthPasswordConfirmLabel: '비밀번호 확인',
    flowAuthPasswordConfirmPlaceholder: '비밀번호를 한 번 더 입력',
    flowAuthPasswordHint: '8자 이상 입력해주세요.',
    flowAuthPasswordMismatch: '비밀번호가 서로 다릅니다.',
    flowAuthEmailInvalid: '올바른 이메일 주소를 입력해주세요.',
    flowAuthShowPassword: '비밀번호 보기',
    flowAuthHidePassword: '비밀번호 숨기기',
    flowAuthProcessing: '처리 중…',
    flowAuthSecurityNote: '비밀번호는 해시로 저장되며 로그인 세션은 보안 쿠키로 유지됩니다.',
    accountMenuLabel: '내 계정',
    accountReplayIntroduction: '소개 다시 보기',
    accountLogout: '로그아웃',
    accountLoggingOut: '로그아웃 중…',
    accountLogoutFailed: '로그아웃하지 못했습니다. 잠시 후 다시 시도해주세요.',
  },
  en: {
    flowHomePasswordPlaceholder: 'Password',
    flowHomeLoginPasswordRequired: 'Enter a password.',
    flowHomeLoginPasswordShort: 'Password must be at least 8 characters.',
    flowHomeLoginPasswordInvalid: 'That password does not match.',
    flowAuthModeLabel: 'Sign in or create an account',
    flowAuthLoginTab: 'Sign in',
    flowAuthSignupTab: 'Create account',
    flowAuthLoginTitle: 'Welcome back',
    flowAuthSignupTitle: 'Start with Flow Math',
    flowAuthLoginLead: 'Sign in to continue into the linear algebra lab.',
    flowAuthSignupLead: 'Create an account with only your email and a password.',
    flowAuthOrEmail: 'or continue with email',
    flowAuthEmailLabel: 'Email',
    flowAuthPasswordLabel: 'Password',
    flowAuthPasswordConfirmLabel: 'Confirm password',
    flowAuthPasswordConfirmPlaceholder: 'Enter the password again',
    flowAuthPasswordHint: 'Use at least 8 characters.',
    flowAuthPasswordMismatch: 'The passwords do not match.',
    flowAuthEmailInvalid: 'Enter a valid email address.',
    flowAuthShowPassword: 'Show password',
    flowAuthHidePassword: 'Hide password',
    flowAuthProcessing: 'Working…',
    flowAuthSecurityNote: 'Passwords are stored as hashes and the session stays in a secure browser cookie.',
    accountMenuLabel: 'My account',
    accountReplayIntroduction: 'Replay introduction',
    accountLogout: 'Sign out',
    accountLoggingOut: 'Signing out…',
    accountLogoutFailed: 'Could not sign out. Please try again.',
  },
  ja: {
    flowHomePasswordPlaceholder: 'パスワード',
    flowHomeLoginPasswordRequired: 'パスワードを入力してください。',
    flowHomeLoginPasswordShort: 'パスワードは8文字以上にしてください。',
    flowHomeLoginPasswordInvalid: 'パスワードが一致しません。',
    flowAuthModeLabel: 'ログインまたは新規登録',
    flowAuthLoginTab: 'ログイン',
    flowAuthSignupTab: '新規登録',
    flowAuthLoginTitle: 'おかえりなさい',
    flowAuthSignupTitle: 'Flow Mathを始める',
    flowAuthLoginLead: 'ログインして線形代数ラボを引き続き利用できます。',
    flowAuthSignupLead: 'メールアドレスとパスワードだけでアカウントを作成できます。',
    flowAuthOrEmail: 'またはメールで',
    flowAuthEmailLabel: 'メールアドレス',
    flowAuthPasswordLabel: 'パスワード',
    flowAuthPasswordConfirmLabel: 'パスワードの確認',
    flowAuthPasswordConfirmPlaceholder: 'パスワードをもう一度入力',
    flowAuthPasswordHint: '8文字以上で入力してください。',
    flowAuthPasswordMismatch: 'パスワードが一致しません。',
    flowAuthEmailInvalid: '有効なメールアドレスを入力してください。',
    flowAuthShowPassword: 'パスワードを表示',
    flowAuthHidePassword: 'パスワードを隠す',
    flowAuthProcessing: '処理中…',
    flowAuthSecurityNote: 'パスワードはハッシュ化して保存され、セッションは安全なCookieで維持されます。',
    accountMenuLabel: 'マイアカウント',
    accountReplayIntroduction: '紹介をもう一度見る',
    accountLogout: 'ログアウト',
    accountLoggingOut: 'ログアウト中…',
    accountLogoutFailed: 'ログアウトできませんでした。もう一度お試しください。',
  },
  zh: {
    flowHomePasswordPlaceholder: '密码',
    flowHomeLoginPasswordRequired: '请输入密码。',
    flowHomeLoginPasswordShort: '密码至少需要 8 个字符。',
    flowHomeLoginPasswordInvalid: '密码不匹配。',
    flowAuthModeLabel: '登录或创建账户',
    flowAuthLoginTab: '登录',
    flowAuthSignupTab: '注册',
    flowAuthLoginTitle: '欢迎回来',
    flowAuthSignupTitle: '开始使用 Flow Math',
    flowAuthLoginLead: '登录后继续使用线性代数实验室。',
    flowAuthSignupLead: '只需邮箱和密码即可创建账户。',
    flowAuthOrEmail: '或使用邮箱',
    flowAuthEmailLabel: '电子邮箱',
    flowAuthPasswordLabel: '密码',
    flowAuthPasswordConfirmLabel: '确认密码',
    flowAuthPasswordConfirmPlaceholder: '再次输入密码',
    flowAuthPasswordHint: '至少输入 8 个字符。',
    flowAuthPasswordMismatch: '两次输入的密码不一致。',
    flowAuthEmailInvalid: '请输入有效的邮箱地址。',
    flowAuthShowPassword: '显示密码',
    flowAuthHidePassword: '隐藏密码',
    flowAuthProcessing: '处理中…',
    flowAuthSecurityNote: '密码会以哈希形式保存，登录会话通过安全 Cookie 维持。',
    accountMenuLabel: '我的账户',
    accountReplayIntroduction: '重新查看介绍',
    accountLogout: '退出登录',
    accountLoggingOut: '正在退出…',
    accountLogoutFailed: '无法退出登录，请稍后重试。',
  },
};

Object.entries(flowHomeLocaleMessages).forEach(([localeKey, messages]) => {
  Object.assign(localeMessages[localeKey], messages);
});
Object.entries(flowHomePasswordLocaleMessages).forEach(([localeKey, messages]) => {
  Object.assign(localeMessages[localeKey], messages);
});

export const localeOrder = ['ko', 'en', 'ja', 'zh'];

export function localeOrderWithPreferredFirst(locale) {
  const preferredLocale = normalizeLocale(locale);
  return [preferredLocale, ...localeOrder.filter((key) => key !== preferredLocale)];
}

const countryLocaleMap = {
  kr: 'ko',
  kp: 'ko',
  jp: 'ja',
  cn: 'zh',
  hk: 'zh',
  mo: 'zh',
  tw: 'zh',
  sg: 'en',
  us: 'en',
  gb: 'en',
  au: 'en',
  ca: 'en',
  nz: 'en',
  ie: 'en',
};

export const presetLocaleNames = Object.fromEntries(
  Object.entries(managedPresetLocaleNames).map(([localeKey, messages]) => [
    localeKey,
    { ...messages },
  ])
);

function inferLocale(value) {
  const raw = String(value ?? '').toLowerCase();
  if (!raw) return null;
  if (raw.startsWith('ko')) return 'ko';
  if (raw.startsWith('ja')) return 'ja';
  if (raw.startsWith('zh')) return 'zh';
  if (raw.startsWith('en')) return 'en';
  const region = raw.match(/[-_](kr|kp|jp|cn|hk|mo|tw|sg|us|gb|au|ca|nz|ie)\b/)?.[1];
  if (region && countryLocaleMap[region]) return countryLocaleMap[region];
  if (raw.length === 2 && countryLocaleMap[raw]) return countryLocaleMap[raw];
  return null;
}

export function normalizeLocale(value) {
  return inferLocale(value) ?? 'ko';
}

export function detectLocale() {
  if (typeof window === 'undefined') return 'ko';
  const urlLocale = new URLSearchParams(window.location.search).get('lang');
  if (urlLocale) return normalizeLocale(urlLocale);
  const pathLocale = localeFromPathname(window.location.pathname);
  if (pathLocale) return pathLocale;
  const stored = window.localStorage?.getItem('linearAlgebraLocale');
  if (stored) return normalizeLocale(stored);
  const browserLocales = navigator.languages?.length ? navigator.languages : [navigator.language];
  const resolvedLocale = Intl.DateTimeFormat?.().resolvedOptions?.().locale;
  const candidates = [...browserLocales, resolvedLocale].filter(Boolean);
  return candidates.map(inferLocale).find(Boolean) ?? 'en';
}

export function t(locale, key, values = null) {
  const template = localeMessages[locale]?.[key] ?? localeMessages.ko[key] ?? key;
  if (!values) return template;
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template
  );
}
